### ISSUE TITLE
Research Topics

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#100]
- [ ] Research Topic Integration testing
- [ ] Research Topic moderation and administration

**Comment by krand7** [comment]
Should we revisit the research topics design next week?

**Comment by remomueller** [comment]
Looks like this will be slated for Release 7.0

**Comment by remomueller** [comment]
@pmanko here's the very rough sketch from our meeting.

![img_0274](https://cloud.githubusercontent.com/assets/316479/7397875/3e3e970c-ee79-11e4-97e4-4debb1c42784.JPG)

**Comment by pmanko** [comment]
Research topic functionality largely implemented. Closing outdated issue, and creating issue #660 for the finishing touches to this feature.
