### ISSUE TITLE
Improve UI on FAQs

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#105]
**Edit:** Improve the way the FAQs are displayed.

**Original** The following was the original issue, but is no longer need.
- FAQs should be list under their own forum
- /forum/faqs and /faqs should both forward to "forum/faqs"
- Each question should be it's own topic

**Comment by krand7** [comment]
@remomueller Is this still a desire?

**Comment by remomueller** [comment]
Hmm, I'm sort of ambivalent about this one. I think we need a better FAQs page that is easier to maintain and keep updated (hence the idea of allowing members or admins to create FAQs), but the forum may be to convoluted.

**Comment by krand7** [comment]
Addressed with bd347943b22b841569764db311fc1b1ca44c6bd3 for 8.0
