### ISSUE TITLE
Daily Trends

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#141]
Members should be able to fill out a daily trends widget on their sleep habits.

**Comment by pmanko** [comment]
@remomueller @krand7 Daily trends were implemented in OpenPPRN. We could use that as a starting point for this issue.

**Comment by remomueller** [comment]
Closing this issue as we want to prevent members from doing busy work, this type of approach would largely benefit from a more automated system. Will recreate new issue with better defined parameters if the needs arise in the future.
