### ISSUE TITLE
BMI and AHI Graph Tool

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#166]
From @susanredline:

> What ever happened to the tool we had to enter height and weight- BMI and see how changes in BMI influence AHI? Would be great to see that back in.

Take a look at making an interactive page where members can plot their BMI, (or calculate it) to see potential changes in AHI with an increase/decrease in BMI.

**Comment by pmanko** [comment]
@krand7 The tool is a bit rough around the edges and needs more educational material to correctly frame what it's showing. If you have time to meet about it next week and decide how to upgrade it and update it's styling, let me know.
