### ISSUE TITLE
Handle presentation of different types of FB feed stories.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#191]
The different types are: 

{STATUS, LINK, CHECKIN, PHOTO, VIDEO}

There are other possibilities for conditional formatting of the stories, including which fields are present etc.

This feature can be implemented when the `In The News` design is updated.

**Comment by mrueschman** [comment]
@remomueller @krand7 At this point, we have removed any incorporation of Facebook/Twitter feeds into the site. Should we close this issue and make another if we revisit these feeds in the future?

**Comment by remomueller** [comment]
Agreed, yes we should close and revisit.
