### ISSUE TITLE
Some users are getting surveys completed even though they have only started or are half done

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#198]
These surveys should be unlocked again so users can complete these surveys.

Potentially add a rake task to `surveys:rake`

```
rake surveys:unlock_incomplete_surveys
```

Since most members have now have missing answers in surveys (due to surveys being restructured), we should provide a message to all users, and unlock the surveys for everyone.

Survey should additionally provide methods to easily `lock!` and `unlock!` surveys
`answer_session.rb`
```ruby
class AnswerSession


  def lock!
    # ...
  end

  # Does not reset answers
  def unlock!
    # ...
  end

end
```

**Comment by pmanko** [comment]
`unlock` method is implemented. Moving to Milestone 5.0 to address when revamping survey system.

**Comment by pmanko** [comment]
This issue has become outdated due to the new system for answer migration and survey presentation.
