### ISSUE TITLE
Survey Redesign: Survey Groups/Tags based on Member's Role

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#200]
Surveys to be restructured (shortened), given a story, provide education per question, and only show relevant surveys.

**Comment by remomueller** [comment]
![img_0080](https://cloud.githubusercontent.com/assets/316479/5707032/7c13e66a-9a53-11e4-9bde-847d28bfa6fc.JPG)
![img_0081](https://cloud.githubusercontent.com/assets/316479/5707031/7c1287c0-9a53-11e4-8373-1d3c2158d712.JPG)

**Comment by remomueller** [comment]
CCing @pmanko, here's the issue for 5.0

**Comment by pmanko** [comment]
This issue is outdated, as role-based surveys have been implemented. Closing issue.

**Comment by remomueller** [comment]
Agreed, this is covered pretty well in the 5.0 survey redesign.
