### ISSUE TITLE
Better Survey Report Feedback (ability to change unanswered questions)

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#205]
Provide users information if they didn’t complete certain questions (i.e., go back and answer this question!), also provide users information if the question isn’t relevant to them due to them choosing a certain option in an earlier question.

**Comment by krand7** [comment]
Users are now automatically redirected if they didn't complete a survey. Moving forward, all questions within a survey will be relevant to them, only full surveys will not be relevant. cc @ekontos
