### ISSUE TITLE
Allow members to have different roles on MyApnea.Org

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#232]
Roles will affect how members interact with each other, what type of surveys they receive, and other changes that can be based on how they view themselves on the website.

- Diagnosed With Sleep Apnea
- Concern That I May Have Sleep Apnea
- Family Member of an Adult with Sleep Apnea
- Family Member of a Child with Sleep Apnea
- Provider
- Researcher

**Comment by pmanko** [comment]
@remomueller - the app uses rolify. Is there a plan to use it for these roles, or are you implementing an in-house solution?

**Comment by remomueller** [comment]
In-House, we'll use a column called `user_type` which allows the user to identify themselves after signup. @krand7 will be designing these prompts and others.

**Comment by remomueller** [comment]
We'll keep `rolify` for the time being for `moderator` and `owner` roles, although in the long run, we may be reducing dependency on gems like `rolify`, `authority` and others to simplify upgrade processes and maintenance.
