### ISSUE TITLE
Review and improve Common Data Model export

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#239]

**Comment by remomueller** [comment]
Create some documentation explaining the methods/classes that are used when attempting to pull data for specific surveys, users, and encounters.

For Example:

Get Race from Survey "About Me" for User1
- Provide iterator that returns
  - If other is filled in, provide the filled in response in the array.
  - ['White', 'CUSTOM RACE']
  - [[White, 1], [Black, 2], [9, 'Custom']]

Height converted to Answer.easy_inches. (combined)

**Comment by pmanko** [comment]
Moving to 5.1 since feature does not involve user interaction.

**Comment by remomueller** [comment]
Reopening just for some additional testing to make sure new PostgreSQL 8.4 views work on staging.

**Comment by pmanko** [comment]
@remomueller I don't think there've been any problems with PostgreSQL 8.4 compatibility recently. Closing issue.
