### ISSUE TITLE
What can providers do on their page?

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#242]
Providers should have a unique set of abilities (e.g. contact network, request data)

**Comment by krand7** [comment]
Dashboard changes with b491599cf155962077a19898c21acf8a960898cf

**Comment by krand7** [comment]
Started with dashboard, but will do full provider rework in the future

**Comment by remomueller** [comment]
cc @mrueschman Closing issue as providers and roles are being removed to improve focus on core user experience.
