### ISSUE TITLE
Allow Admins to add Comments on User Accounts

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#258]
Some accounts are fake, and generate emails being bounced when the user participates on the forum.

We could do a couple things:

(a) Allowing admins to set notes on accounts to why they were deleted or had emails disabled.
(b) Require some sort of "slow" email confirmation process (not an immediate on that is currently in place with devise) Having users confirm their emails after some time (delayed email confirmation)
(c) Limiting amount of posts a user can do with an unconfirmed email

**Comment by krand7** [comment]
Closed with 623bac2662dd01b41253dc3dee47b99a51d08b1e
