### ISSUE TITLE
Transition pages to new UI (beta)

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#261]
Currently, all tests are ran on the existing template. Tests should be added for the beta versions of the following pages
- [x] Home
- [x] Community
- [x] Forums
- [x] Research Surveys
- [x] Rank the Research
- [x] Account

**Comment by remomueller** [comment]
We'll be transitioning to the new UI (beta) for the 5.0.0 release. We'll do this by deprecating (but not removing) the original UI. Tests should now only cover the new UI (whether or not the user has the beta opt in or not). The beta opt in should be relabeled to "Opt Me In To Future Betas" for the time being.

**Comment by remomueller** [comment]
Also, feel free to add pages that still need to be transitioned to the top of this list and reference issues that are relevant to this as tests/pages are updated. For example, I'm crossing off **Forums** as it uses the new UI exclusively at the moment.

**Comment by krand7** [comment]
Rank the research now exclusively uses the new UI, crossing it off!

**Comment by pmanko** [comment]
Registration flow is beta, and we can update the backend code and replace all views with the beta views.
