### ISSUE TITLE
Emails will need a "salutation" partial

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#290]
Sign up form currently asks for first and last name. In the near future, we will no longer be requiring name on the sign up form (will be asked later), and most emails start with:

```haml
Dear @user.first_name
```

The salutation header should be placed in ALL emails and be something like:

```haml
- if @user.first_name.present?
  Dear @user.first_name
- else
  Dear MyApnea.Org Member
```

cc @krand7

**Comment by krand7** [comment]
Will continue to require first_name and last_name for signups, so this is unnecessary :)
