### ISSUE TITLE
Enable Turbolinks in JS manifest file

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#294]
- [ ] Event handler attachment should user `$('document').on()` function. See http://api.jquery.com/on/.
- [ ] Turbolink-specific events such as `page:load` should be used in parallel to document events. See https://github.com/rails/turbolinks#events

Remo: Essentially enable turbolinks, and make all JS that needs to run on page load, go into a "ready()" type function. Ex: `surveysReady()` added to the bottom of the `main.coffee` `ready()` function.

**Comment by pmanko** [comment]
@remomueller do you think we should re-enable turbolinks sometime in the future, or at least make the javascript compatible in case we decide to? If so, is there anything you'd like to add to this issue?

**Comment by remomueller** [comment]
Turbolinks is definitely something we want to enable. We should be able to start enabling it during the current release cycle to see how it affects everything. We have put the `ready()` functions in place, so we shouldn't have to modify too much to make everything work as intended.

**Comment by remomueller** [comment]
Reopening, and changing to "Enable Turbolinks" in `cleantheme.js`

**Comment by remomueller** [comment]
CC @krand7 @pmanko we'll do a review of this before it's closed.
