### ISSUE TITLE
When typing in a hidden input field for a radio button, keystrokes are not filtered out.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#295]
Pressing any of the hotkey letters causes the input to lose focus and the radio button to change it's value.

**Comment by krand7** [comment]
@pmanko this was the reason for the use of the special-case changeFocusDirect function. It's been working fine, I assume you're playing around with this in response to issue #292

**Comment by pmanko** [comment]
@krand7 Sorry about that, I didn't think I changed when changeFocusDirect was called. 

When you get a chance, could you take a look through the most recent [surveyAnimation.js.coffee file](https://github.com/myapnea/www.myapnea.org/blob/5-0-dev/app/assets/javascripts/cleantheme/surveyAnimation.js.coffee)? Everything seems to be working except for the keystroke filtering issue for radio buttons, and I'm not sure how I broke it. I might not be adding the hidden inputs to radio buttons correctly, since I tested it before only on checkbox inputs. 

I also am now submitting answers on input `.change` events instead of in the `nextQuestionScroll` function. This seems to be working well, except that I had to add custom triggers for changes to radio button inputs, as they are indirectly changed with javascript, which does not trigger the event.

**Comment by krand7** [comment]
Nice! I started doing the same thing with .change events, but noticed the same issue with custom events on radio buttons, so used a temporary fix in 1500ebb77895a29f28b77d97033fc7a8bf24dedb and 7beea73670d78f4684ff66d32c6319931121d836. Glad you got it working!

You're right, the current js file is probably too specific to have picked up on hidden fields with the radio input. I'll clean it up a bit and make sure it works, and will be more adaptable in the future.

**Comment by remomueller** [comment]
Just a thought, Firefox handles .change events differently than other browsers (especially when navigating backwards to an existing page), so we may want to add this as a specific thing to check for in the `test/integration/integration_checklist.md` that @pmanko has compiled.

**Comment by krand7** [comment]
All is set on the front end, @pmanko can you address @remomueller 's suggestion to make tests for this?
