### ISSUE TITLE
For Consideration: Revisiting a survey where you left an answer blank

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#298]
Users who submit surveys (that are then locked), that contain blank responses, should be able to go back and add responses to those responses that were left blank.

However, other responses should be displayed as "locked" or uneditable, as we don't want users to be able to change research data once it's submitted.

This may also help down the line if new questions are added to existing surveys, to allow users who submitted a survey to go back and add info into the newly added questions.

**Comment by krand7** [comment]
Closed during survey overhaul and following discussions - last point is more or less irrelevant now.
