### ISSUE TITLE
Add terms of access for provider registration

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#308]
From @ekontos 

<code> The Terms of Access is ready for incorporation in the provider portal (attached). The idea is that providers will need to agree to this before seeing any aggregate data.

**Comment by remomueller** [comment]
This should be modeled similar to how the Consent and Privacy Policy is currently modeled.

**Comment by pmanko** [comment]
From authorization perspective: 
- You need to be a registered user and have accepted a consent or have accepted a terms of access.
- If you have consent, you can view report page
- If you try to visit the report page but don't have a consent or TOA, you will be asked to accept a TOA

**Comment by krand7** [comment]
Created issue for new design of index page at #314
