### ISSUE TITLE
Change recent news section 

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#317]
Can begin pulling from MyApnea.Org facebook page (https://www.facebook.com/MyApnea) once this page gets populated

**Comment by krand7** [comment]
@ekontos Can you write up a few posts for the following topics to be included on the news highlights?
- [ ] New surveys post
- [ ] The need to select a role
- [ ] Patient engagement panel update

**Comment by ekontos** [comment]
done. posts are currently hidden

________________________________

**Comment by krand7** [comment]
Actual links updated as a part of 1d824e99b556342bd73059dcea31bcdc0da4e91d
