### ISSUE TITLE
All surveys should have yml files created

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#319]
- [x] About Me
- [x] Additional Information About Me
- [x] About My Family
- [x] My Sleep Pattern and Sleepiness
- [x] My Sleep Quality
- [x] My Health and Quality of Life
- [x] My Sleep Apnea
- [x] My Sleep Apnea Treatment
- [x] My Risk Profile
- [x] My Health Conditions
- [x] My Interest in Research

**Comment by krand7** [comment]
@remomueller @mrueschman I would avoid feedback on the three unchecked surveys for now - there are outstanding questions and don't want you to waste your time for something that will likely change! Will alert when we get answers from Susan.

**Comment by remomueller** [comment]
Is "My Quality of Life" the "My Health and Quality of Life" above, which title should be used?

**Comment by krand7** [comment]
'My Sleep Apnea Treatment' added with new layout in a491b4657305cd5b6284dbf80592af487448f370
