### ISSUE TITLE
Refactor cleantheme stylesheets and js/coffeescript files into main application structure and clean out old files.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#321]

**Comment by pmanko** [comment]
@krand7 This is not high priority at all, but I was looking through the stylesheets and javascript folders, and a lot of the stuff in there can be removed. Also, `cleantheme` is now the default theme, so we can reduce the complexity quite a bit.

**Comment by krand7** [comment]
Break up css into smaller files (components), use .on more consistently in coffeescript files
