### ISSUE TITLE
Link Rank the Research item to results post

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#323]
Once a question is approved and selected as monthly topic, the question should link to the generated forum post

**Comment by krand7** [comment]
@remomueller What is currently happening when a topic is selected? Is it marked as completed?

**Comment by remomueller** [comment]
I think the topic has a `state` associated with it.

```ruby
STATES = [:under_review, :proposed, :accepted, :rejected, :complete, :hidden]
```

You'll have to ask @pmanko at what the difference is between `under_review` and `proposed`, but the others seem to go as follow:

1. A user submits a research topic, and it gets marked `under_review` (default).
2. A moderator marks the topic as `accepted` or `rejected`.
3. Accepted topics are visible by everyone on the Rank the Research Page
4. A research topic is then chosen, and is set as `complete` and shows up somewhere else (to be determined).

The two states that I'm not sure we need are `proposed` and `hidden`, as I can't see why something would need to be hidden when it can be rejected or deleted.

**Comment by krand7** [comment]
Currently accepted research topics are presented in research highlights, as per #676, but we need to revisit this when we link new proposed research topics to their results page
