### ISSUE TITLE
Move tmp files generated by migrate_old_answers to rails_root/tmp

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#327]
In the `lib/classes/answer_migration.rb:201-206`:

Remove hard-coded path, and replace with `<RAILS_ROOT>/tmp/surveys/`. Use [FileUtils.mkdir_p](http://ruby-doc.org//stdlib-2.2.0/libdoc/fileutils/rdoc/FileUtils.html#method-c-mkdir_p) to create the survey directory if it doesn't exist.

**Comment by pmanko** [comment]
Not applicable since no files are created anymore.
