### ISSUE TITLE
Turbolinks preventing loading Surveys/14/Report

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#331]
https://sleepepi.partners.org/edge/www.myapnea.org/surveys/14/report

After creating a new user (provider), I had 3 surveys that were all 1/3 complete, that said "View Data". Also, clicking "View Data" didn't load using turbolinks, (opening in a new tab with url did work)

**Comment by remomueller** [comment]
Looks like it may be a turbolinks issue, since it's not displaying the "consent" page.

Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://172.27.111.193/edge/www.myapnea.org/consent' cannot be created in a document with origin 'https://sleepepi.partners.org'.

This looks like it's creating the URLs incorrectly (due to firewall).

**Comment by remomueller** [comment]
It's possible that `request.fullpath` is the root of the issue, if it doesn't have the correct host name set.

**Comment by remomueller** [comment]
It also looks like I can't actually view https://sleepepi.partners.org/edge/www.myapnea.org/surveys/14/report after accepting the consent

**Comment by remomueller** [comment]
This could also be potentially caused by the fact that reports shouldn't be loaded by id (ie 14), but instead use a `slug`

**Comment by pmanko** [comment]
Closed - previous generation surveys will not be available for viewing or completion by users.
