### ISSUE TITLE
Can't see "About My Family" Report

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#341]
It seems to be redirecting me to the surveys index.

https://sleepepi.partners.org/edge/www.myapnea.org/surveys/about-my-family

https://sleepepi.partners.org/edge/www.myapnea.org/surveys/about-my-family/report

**Comment by remomueller** [comment]
I entered a couple of very high values for household and people who live in home, so perhaps that affected it.

**Comment by remomueller** [comment]
Looks like the survey isn't being flagged as complete for some reason:

![surveys-completed-about-my-family](https://cloud.githubusercontent.com/assets/316479/6334619/d21c6308-bb63-11e4-9886-fd2c33d3e900.png)

**Comment by krand7** [comment]
Mentioned to @pmanko last week and referred to here: 318

Any thoughts Piotr?

**Comment by pmanko** [comment]
Fixed with recent survey model updates, including in commit c66d3823094d62d877dee76838538fdf523db0aa
