### ISSUE TITLE
My  Sleep Apnea Treatment Question typo

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#343]
It looks like the "What treatment(s) are you currently using for your sleep apnea?" question has a question that's not entirely correct in the description of BiPAP.

> BiPAP (Bi-level Airway Pressure Machine)

Should this be:

> BiPAP (Bilevel **Positive** Airway Pressure Machine)

See here: http://en.wikipedia.org/wiki/Bilevel_positive_airway_pressure

cc @mrueschman for clarification

**Comment by krand7** [comment]
This was just built quickly for a mockup to send to Susan - waiting on approval before fleshing the question out. Will be sure to fix.

**Comment by remomueller** [comment]
Ok, also see #344
