### ISSUE TITLE
"My Sleep Pattern" extra Epworth question needs additional option (or to be removed)

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#346]
"While Driving" is not an actual question on the Epworth, and when this question is presented on paper it often befuddles people who do not drive. Sometimes an additional option, "I do not drive", was added to the question for people to check.

I would consider removing the question completely because it is not an actual part of the ESS.

**Comment by remomueller** [comment]
This looks like a question for @ekontos to address.

**Comment by ekontos** [comment]
That's fine to remove if it is not a part of the ESS.
