### ISSUE TITLE
My Quality of Life survey

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#347]
Since **eleven** is a writable number, perhaps we should stick with it written out, as opposed to arabic numerals.

> MyApnea.Org is one of ~~11~~ **eleven** patient-powered research networks (PPRNs). The following questions are asked by all PPRNs. Researchers can use this information to make comparisons between different illnesses and diseases.

cc @mrueschman to see if he agrees.

**Comment by krand7** [comment]
If pcornet plans on giving more grants, I would prefer to write something more generic to cover ourselves for the future. Thoughts?

**Comment by remomueller** [comment]
I think that would work as well.

**Comment by mrueschman** [comment]
Generic seems fine. I always followed the common rule of `Spell out numbers under 10 (zero through nine), and use the numeric symbols for numbers 10 and up.`, so I would have disagreed with the original premise of this issue. :cake:

**Comment by remomueller** [comment]
Ah thanks @mrueschman, I remember you mentioning something along those lines. @krand7 use Mike's rule of thumb in the future, so we're consistent on these types of things. Thanks!
