### ISSUE TITLE
For user's who have "100%" all surveys, perhaps congratulations on being complete, and point them to create research questions.

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#352]
After completing all surveys, users may have an understanding of what type of research questions could be asked, so lead them to create a research question of their own.

This is open for discussion.

**Comment by remomueller** [comment]
cc @mrueschman

**Comment by mrueschman** [comment]
I think people should be congratulated for sure!

As for allowing them to submit potential questions.. I don't see getting much value added from something like this at this time. In the future, I could perhaps see having a survey of user-submitted questions, which might be sort of interesting. Probably too much time (now) to build something like that with a very low immediate impact.

**Comment by remomueller** [comment]
It would essentially link to this page (which already allows users to submit research questions for rank the research):

https://sleepepi.partners.org/edge/www.myapnea.org/research_topics/new

**Comment by mrueschman** [comment]
Oh, I thought you might be talking about something different from Rank the Research, like the patients proposing actual questions that could be on a future Survey. The Rank the Research questions are sort of "larger" questions that you'd build a project/study around. 

In that case, I think there could be some sort of transition that points 100% completers over to Rank the Research for them to continue their contributions to the effort.
