### ISSUE TITLE
My-sleep-apnea-treatment survey does not allow completion of first question

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#356]
The first question (checkbox-input), will not be registered as 'complete'. Possible error with json request? Possibly expecting a hidden input? 

Current version: a491b4657305cd5b6284dbf80592af487448f370

**Comment by pmanko** [comment]
@krand7 I can't seem to replicate this. Choosing any option in the `What treatments are you currently using` causes the green bubble to fill in and mark the question as complete. 

What situation did you run into this error in?
