### ISSUE TITLE
Change error message for over 18 checkbox not being selected

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#358]
From #302

**Comment by pmanko** [comment]
@krand7 Here's a temporary fix for formatting the error messages for the user:

```ruby
              - resource.errors.messages.each do |key, msg|
                - if key == :over_eighteen
                  %li= msg.join(", ")
                - else
                  %li= "#{key.to_s.titleize} #{msg.join(", ")}"
```

Rails, by default, appends the name of the field to the beginning of the message in `errors.full_messages`, even for custom messages.

Our definition:  `user.validates :over_eighteen, inclusion: { in: [true], message: "You must be over 18 years of age to sign up." }`), 
was still causing "Over eighteen" to be appended to beginning of this message. 

This is something to keep in mind when we make a consolidated solution for displaying form validation errors.
