### ISSUE TITLE
Make surveys responsive to numpad hotkeys

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#359]
From #302

**Comment by pmanko** [comment]
Could be related to DOB entry problems in the `about-me` survey, as submitted by a couple of users.

**Comment by krand7** [comment]
Could be fixed using only `e.which`, will test on keyboard tomorrow morning

**Comment by krand7** [comment]
Issue: numpad character codes are values 96-106, while top-row character codes are values 48-58. surveyAnimation takes this into account now
