### ISSUE TITLE
Hidden input as radio_input rather than text_field

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#366]
We discussed this before but an issue was never made. Currently, the secondary input automatically creates a text_field, but we want to infer the secondary input type correctly.

File can be found in '_secondary_input.html.haml'

**Comment by pmanko** [comment]
@krand7 on it!

**Comment by pmanko** [comment]
@krand7 I added the radio input support to `_secondary_input.html.haml`. See 49a1c4b for details. Handing it over to you for styling/behavior cleanup. The new input shows up for the `about-my-family` survey.
