### ISSUE TITLE
From PCORNet Common Data Model for "About Me Survey"

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#373]
01=American Indian or Alaska Native
02=Asian
03=Black or African American
04=Native Hawaiian or Other Pacific Islander
05=White
06=Multiple race
07=Refuse to answer
NI=No information
UN=Unknown
OT=Other

**Comment by remomueller** [comment]
This will split Race and Ethnicity into two questions for this survey.

**Comment by pmanko** [comment]
@krand7 let me know when this update happens, since I will have to update answer migration mappings.

**Comment by krand7** [comment]
@pmanko sounds good! All questions have been approved by @ekontos, and are waiting on Susan's approval now. Should be ASAP

**Comment by krand7** [comment]
@pmanko The new ethnicity question appeared when I ran this on my localhost, but the answer options did not appear. This had happened before and I think you resolved it -- do you know off-hand what causes it?

**Comment by pmanko** [comment]
@krand7 I hopefully solved this issue with commit 3c39a7817139b9b2ea2789329cd6287eadea5de5 - it had to do with naming conflicts between the fixtures and survey files.

**Comment by krand7** [comment]
Reloaded my database and it worked fine on my computer!
