### ISSUE TITLE
Add StopBANG! survey for at-risk patients

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#375]

**Comment by krand7** [comment]
@ekontos @remomueller Moving this to release 8, as that's when we'll be doing the next batch of surveys and testing new survey launch

**Comment by remomueller** [comment]
Need to revisit if this is useful enough to include for researchers, or if there is a better way to capture data for at-risk patients. Also, current focus is on diagnosed patients, moving out of 8.0 for time being. Can revisit.

**Comment by krand7** [comment]
8.0 introduced survey builder - research team working on creating relevant surveys.
