### ISSUE TITLE
Forum Restructuring

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#377]
- General
  - This is for new users, for all types of discussion, meeting place, etc)
  - This would take place of the “Introductions” forum.
  - Tell Your Story

- News
  - Research Blog Posts
  - Results of Rank the Research
  - Lottery Winners
  - PEP Recruitment
  - Site feature descriptions

- Rank of Research
  - Will improve with 7.0

- Stickied Posts (README FIRST!)

- Your Feedback
  - This would replace “Building MyApnea.Org”
  - I’m not sold on “Website Suggestions” but we need something that encourages users to think about what they would like to see on the site, and how they could influence research on MyApnea.Org
  - I don’t feel that any of the existing topics really belong in this area.

**Comment by remomueller** [comment]
We should make sure that the old forum slugs forward to the new forum slugs for a time of about a month or so.

**Comment by krand7** [comment]
All that's left is to change the actual slugs once 5.1 goes live

**Comment by remomueller** [comment]
I've added this to the following to the release script:

```ruby
  Forum.find_by_slug('introductions').update(slug: 'general')
  Forum.find_by_slug('rank-the-research').update(slug: 'research')
```
