### ISSUE TITLE
Default encounter should be `baseline` instead of `registration` and `blank` or `nil` in scope validation should not be allowed

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#380]
We want to keep more with the study terminology when launching surveys.

- `baseline`
- `followup1`
- `followup2`

Also, NEW answer sessions should not allow a `blank` or `nil` encounter. Old one's should maybe set to something for example `release-4`, to make sure they pass the validation. These would also not show up since we're not showing the old deprecated surveys that they would be associated with.

cc @pmanko @krand7

**Comment by pmanko** [comment]
@remomueller is there anything else I should change besides the changes in d7e6f03?

**Comment by remomueller** [comment]
@pmanko this looks good, did we decide if we wanted a migration of old AnswerSessions to be called something? Do you have any thoughts on what we should do for those?

**Comment by pmanko** [comment]
@remomueller I think this depends on what we want users to be able to do with the migrated data. If we want them to still be able to finalize/submit the surveys in question on their dashboard, then we should just use the `baseline` encounter in migrations and lock the migrated answers.

**Comment by remomueller** [comment]
@pmanko I'm referring to existing AnswerSessions for Surveys 13, 14, and 15, which are getting deprecated. I don't think users would see these answer sessions any more, as they would have new one's created for any surveys they get assigned which would then be `baseline` as your suggesting. You did mention that the AnswerMigration does not replace the old AnswerSessions, correct?

**Comment by pmanko** [comment]
Yes, but it currently marks newly created ones with a "migrated" encounter. I might change it to "baseline" and make the migrated answer sessions available to be used just as if they were started but not completed. 

For answer sessions for previous surveys, I think we should manually tag them with the encounter you suggested.

**Comment by remomueller** [comment]
Sounds good, let's make the newly migrated ones say `baseline`, otherwise we'd run into issues with duplicate surveys for the users when they set their role, as it would attempt to assign them another one under `baseline` encounter which would then not exist (but we want it to).
