### ISSUE TITLE
Text inputs should be optional with a 'prefer not to answer' option

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#383]
For questions such as: DOB, height, weight

**Comment by krand7** [comment]
@pmanko Partial is up. I can work on #373 (new demographic questions) now so you can focus on the backend here

**Comment by pmanko** [comment]
@krand7 I did most of the backend work and added testing for this feature. I'll extract it into a partial - this way, it can be used in any question template. In the future, we might even use this in categorical questions instead always adding `prefer not to answer` in the answer options.

**Comment by pmanko** [comment]
@krand7 handing it over to you for style fixes, etc. You can close the issue when you're happy with it.

**Comment by krand7** [comment]
@pmanko Styling is set, but when I refresh the page it's currently inferring that it's checked. This might have to do with the params passed into the checkbox_tag function, can you check this?
