### ISSUE TITLE
Implement a logical progression through surveys after initial `about-me` survey is completed

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#389]
As requested by Susan Redline

**Comment by krand7** [comment]
Current progression is alphabetical, and it is fairly logical (at least the first three surveys). We can talk with @ekontos about the order!
About Me -> About My Family -> Additional Information About Me -> My Health Conditions -> My Interest in Research -> My Quality of Life, etc...

**Comment by ekontos** [comment]
Needs reordering

On Mar 2, 2015, at 9:22 AM, "Kyle Rand" <notifications@github.com<mailto:notifications@github.com>> wrote:


Current progression is alphabetical, and it is fairly logical (at least the first three surveys). We can talk with @ekontos<https://github.com/ekontos> about the order!
About Me -> About My Family -> Additional Information About Me -> My Health Conditions -> My Interest in Research -> My Quality of Life, etc...

—
Reply to this email directly or view it on GitHub<https://github.com/myapnea/www.myapnea.org/issues/389#issuecomment-76719245>.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by krand7** [comment]
About me
Additional information about me
About my family
my health conditions
my interest in research
my quality of life
my risk profile
my sleep apnea
my sleep apnea treatment
my sleep pattern
my sleep quality

**Comment by krand7** [comment]
New layout:

#### AT_RISK
About me
Additional information about me
About my family
My health conditions
My sleep pattern
My sleep quality
**My risk profile**
My quality of life
My interest in research

#### DIAGNOSED
About me
Additional information about me
About my family
My health conditions
My sleep pattern
My sleep quality
**My sleep apnea**
**My sleep apnea treatment**
My quality of life
My interest in research
