### ISSUE TITLE
IE10 Clicking "Home" from Account Settings brings user to landing page

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#398]

**Comment by krand7** [comment]
It doesn't log you out, but actually incorrectly loads the landing page. Refreshing the page correctly reloads the home page. Tested on production, and it wasn't working this way in 4.0

**Comment by remomueller** [comment]
Not able to reproduce this at the moment using IE11 to emulate IE10, tried both development and staging environments. Moving this to 5.1 as it's not a critical bug.

**Comment by krand7** [comment]
Tested on production 5.0 and still could not replicate, maybe an Apache+Turbolinks bug? Closing!
