### ISSUE TITLE
Currently surveys on the dashboard aren't showing the percentage complete correctly

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#404]
These are all possibly closely related, so making a single issue:

- “Percent Complete” on surveys after migration should be correct (not zero)
- Migrated Choices should be “locked”
- Birth Date field should use correct format (mm/dd/yyyy)

**Comment by pmanko** [comment]
I noticed one more error in migrating values into answers with more than one answer template. Since the 2nd template is mapped to another question, that value never gets migrated due to the existing answer check. The check should be for existing answer/answer_template combo.
