### ISSUE TITLE
Pointer-events none not working in IE

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#413]
Found while testing IE8 #406

**Comment by krand7** [comment]
This was related to the surveys being locked. In IE8, users can go back and view locked surveys, and are still able to click on the answers and it will appear that they change, but they won't actually save on the backend. I'm removing the milestone and bug label, as it's not actually affecting data or a large proportion of users, and will revisit at a later date.

**Comment by mrueschman** [comment]
Closing -- no longer supporting IE8.
