### ISSUE TITLE
Locked survey indicators cause auto-scroll and submission bugs

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#414]
- [x] `submit survey` button on the bottom does not update correctly for migrated surveys. The status circles work, but there's no change when pressing submit. The javascript UX likely has to be updated for migrated answers.
- [x] Focus sometimes jumps to already-locked questions.

**Comment by remomueller** [comment]
Moved part of this issue to Release 6.0: Issue #431
