### ISSUE TITLE
Nested Categorical Questions (Reports)

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#431]
From @pmanko 

> The survey reports for nested categorical questions (like the number of family members diagnosed in the about-my-family survey) do not display correctly.

**Comment by pmanko** [comment]
@krand7 @remomueller What's the status on this issue?

**Comment by krand7** [comment]
I'm looking through it now. It's only true with the old reports, but these are still visible so we should make sure they display

**Comment by remomueller** [comment]
@krand7, I thought only one of the old survey reports would still be visible?

**Comment by krand7** [comment]
Members have the option to go back and see these reports, and researchers/providers will all see these old reports first
