### ISSUE TITLE
On iPhone 5, text in orange headers often does not fit and wraps onto multiple lines

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#439]
![2015-03-04 08 49 43](https://cloud.githubusercontent.com/assets/707167/6484997/6e7f369e-c24e-11e4-957c-d274792fcfcb.png)

**Comment by remomueller** [comment]
Also from SR:

> On my iPhone the yellow block on top hides words such as name and other text on second line on top yellow block
