### ISSUE TITLE
Yes/No questions on surveys should use either all numeric or all character keyboard shortcuts

### ISSUE THREAD

**Issue by mcailler** [myapnea/www.myapnea.org#449]
Example: My health conditions survey
![screen shot 2015-03-05 at 9 30 31 am](https://cloud.githubusercontent.com/assets/1759957/6506728/1ca39a36-c31b-11e4-900b-222597b0b684.png)

**Comment by krand7** [comment]
@pmanko If I leave the actual values as is, I can change the hotkeys without any issues matching data?

The general idea will be to make all hotkeys consistent so that:
- **Categorical** questions use: **Letters**
- **Rating/ranking** questions use: **Numbers**

**Comment by pmanko** [comment]
@krand7 I believe so. I don't use hotkeys for anything else.
