### ISSUE TITLE
Show more than 8 providers per page, and add pagination to show more, and a search box as well.

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#460]
- [x] Number of providers per page
- [x] Search box
- [x] Pagination

**Comment by krand7** [comment]
Pagination is all set! Search functionality can be included at a later date

**Comment by remomueller** [comment]
@ekontos mentioned that a search box should be added as well.

**Comment by krand7** [comment]
Closing this and moving discussion to new issue #613

**Comment by remomueller** [comment]
This only has the search box remaining, the other issue is more related to how to filter and sorting users using name/location.
