### ISSUE TITLE
Pseudo Code for Co-Enrollment API

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#476]
The co-enrollment seems to need four fields to work with an API:

`health_eheart_token`: Created by MyApnea.Org for participants in MyApnea.Org that are sent to Health eHeart Registration via unique URL
`myapnea_token`: Created by Health eHeart for Health eHeart participants sent to MyApnea.Org via unique registration URL

`health_eheart_user_id`: Managed by Health eHeart, an obfuscated participant id shared to other partners to identify an individual in Health eHeart
`myapnea_user_id`: Managed by MyApnea.Org, an obfuscated participant id shared to other partners to identify an individual in Health eHeart

Here is an example workflow (end goal) MyApnea.Org send a participant to Health eHeart:

1. MyApnea.Org generates `health_eheart_token`s for each member of MyApnea.Org
2. MyApnea.Org uses the `health_eheart_token` to generate a unique URL for each member, sending them to unique Health eHeart registration page.
3. The member registers on Health eHeart, and Health eHeart assigns the member a `health_eheart_user_id`.
4. Health eHeart sends a POST request to MyApnea.Org with contents of `health_heart_token`, and `health_eheart_user_id`.
5. MyApnea.Org responds to POST request with one of the following (JSON):
- a. The token isn’t found in MyApnea.Org, ex: { error: “notokenfound” }
- b. The token is found and linked to a user. MyApea.Org maps `health_eheart_user_id` to its members id, and then sends back the `myapnea_user_id` to Health eHeart servers, ex: { myapnea_user_id: ‘12345’, health_eheart_user_id: `506060` }

The other direction would work in a similar manner, i.e. Health eHeart sends participant to MyApnea.Org

1. Health eHeart generates `myapnea_token`s for each member of Health eHeart
2. Health eHeart uses the `myapnea_token` to generate a unique URL for each member, sending them to unique MyApnea.Org registration page.
3. The member registers on MyApnea.Org, and MyApnea.Org assigns the member a `myapnea_user_id`.
4. MyApnea.Org sends a POST request to Health eHeart with contents of { `myapnea_token`, and `myapnea_user_id` }
5. Health eHeart responds to POST request with one of the following (JSON):
- a. The token isn’t found in Health eHeart, ex: { error: “notokenfound” }
- b. The token is found and linked to a user. Health eHeart maps `myapnea_user_id` to its members id, and then sends back the `health_eheart_user_id` to MyApnea.Org servers, ex: { health_eheart_user_id: ‘506060’, myapnea_user_id: `12345` }

**Comment by mrueschman** [comment]
Tentatively adding back into 8.0, primarily to make sure it stays in the foreground and we dedicate more discussion to it in the coming weeks.

**Comment by remomueller** [comment]
Base functionality is in place, reassigning to @krand7 for nicer UI :tada:

**Comment by remomueller** [comment]
Closed in release 10.0.0
