### ISSUE TITLE
IRB report numbers for administrators

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#481]
**Health / Medical Information Data Collection**

How many health/medical records have been included in the repository to-date?  Enter numerials only.

How many research projects have utilized the data from the repository?  Enter numerials only.

 
How many subjects have withdrawn their data from the repository to-date?

**Comment by krand7** [comment]
@remomueller @mrueschman is this a thing?

**Comment by mrueschman** [comment]
Not entirely sure.. do you know the origin of this, @remomueller ?

**Comment by remomueller** [comment]
@mrueschman @krand7, this was a type of report requested by @susansurovec and @ekontos. I haven't heard any followup since March, so I'm guessing we can close for the time being until it's needed for a more specific purpose again in the future.
