### ISSUE TITLE
Engagement and Retention Reports for Administrators

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#482]
From @ekontos 
> For now if we can calculate number of community interactions (posts, votes etc) with survey completes we could start with that.

**Comment by remomueller** [comment]
Here's some more thoughts:

I would think that completed surveys can only be measured in terms of retention if the participants do followup surveys as well. We haven’t launched any followups yet, although we have a 6-month followup scheduled in a couple of months.
 
We may be able to do some more reports on correlation between # of forum posts vs surveys completed as well.
 
I think along with **retention** (time component) being defined, we may want to carefully define user **engagement** (no time component) as well. I think we could put together a quantitative metric to compare users across the site using this.

**Comment by krand7** [comment]
Closed with release 7.3
