### ISSUE TITLE
Submitting survey answers on Firefox/IE causes right-side bar to get pushed off page

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#491]
Seems to happen in Firefox (latest) and IE 11. Not in Chrome. Makes the right-hand column unusable until you visit a subsequent page.

![2015-03-23_09h44_56](https://cloud.githubusercontent.com/assets/707167/6781100/46db8348-d141-11e4-8433-4bfac9ad04eb.png)

![2015-03-23_09h45_37](https://cloud.githubusercontent.com/assets/707167/6781108/5f0792ea-d141-11e4-8779-6445584aedb5.png)

**Comment by remomueller** [comment]
Wonder if this is related to #648.

**Comment by remomueller** [comment]
Moving to 8.0 as underlying issue needs restructuring of the layouts.

**Comment by krand7** [comment]
Closed with switch to fixed-width layout and removal of sidebar for surveys with 9.0
