### ISSUE TITLE
BMI/AHI tool Feedback

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#503]
From @danmobley:

> 1. In the top, remove the apostrophe before the word obesity.  In the second sentence, change the work Hypoxia to Hypopnea—Apnea Hypopnea Index.  Might consider rewording to:  Although obesity is not a trait of all patients with sleep apnea, there is evidence that a relationship between weight and sleep apnea exists.  Changes in weight have been linked to changes in the Apnea Hypopnea Index.
2. I like to concept, but the “Effects of Weight Change on AHI” might be confusing to some.  Especially because feedback is in percentages.  Clinically, we would talk about a patient losing xx pounds or having a reduction in AHI of xx events per hour.  I do think asking desired weight and then showing the BMI on a scale if the patient reaches a desired weight is interesting.

**Comment by krand7** [comment]
Removed AHI components with b2d327d497457385408f7111075b90d85bae44f7
