### ISSUE TITLE
Moderators should be able to move Forum Posts and send email to user to inform of the move

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#505]
In order to better accommodate users who may post in an incorrect area on the site, we will be providing moderators a way to move these posts. A couple of things to note is that it is important to inform the user that the post has been moved (this may be an automated email), and may also include reasoning for the move. “Dear User, Moderator Remo has moved your post to Topic “My CPAP Mask Leaks” because your post is relevant and contributes to the specific topic.” This was something we didn’t implement initially as it wasn’t clear how to inform users of the move of the topic, and we thought it would disrupt other topics. It turns out that our current method of approving the off-topic post on the current topic ended up disrupting those topic threads. (Can’t win them all, I guess!)

**Comment by krand7** [comment]
Moderators can move topics between forums, and with new approval process (posts are already visible) and ability to comment on individual post, this is now a now-issue.
