### ISSUE TITLE
Expand CDM export to include CONDITION table

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#518]
In CDM 2.0 a `CONDITION` table was added. These can be taken from the `My Health Conditions` survey, question 1.

We have:

- PATID
- REPORT_DATE (can be date survey submitted)
- CONDITION (for now, just put `Allergies`, `Stroke`, from the question itself etc.)
- CONDITION_TYPE (OT for "Other")
- CONDITION_SOURCE (PR)

![2015-04-01_16h33_40](https://cloud.githubusercontent.com/assets/707167/6951976/dc368cba-d88c-11e4-8d69-4081e282bb73.png)
![2015-04-01_16h33_50](https://cloud.githubusercontent.com/assets/707167/6951983/e1cd75bc-d88c-11e4-977d-b389f38ef32c.png)

**Comment by remomueller** [comment]
Hi @pmanko, if possible this could get included in 6.0, if not move to another milestone. Thanks!
