### ISSUE TITLE
BMI tool should have a button to 'Calculate' bmi

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#527]
For backwards compatibility and cross-browser support for "blur"

**Comment by mrueschman** [comment]
Yes, users should have to click a button after inputting their desired weight.

The "Calculate minimum healthy weight" is also confounding:

1. Presumably the "minimum" healthy weight would be my weight at at BMI of 18. I think the intention of the button is something like, "Use Normal BMI weight".
2. I think you should use a BMI of 24.9 for this calculation, as it is in the normal range.
