### ISSUE TITLE
In the 'about my family' report, family members could be different sizes

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#534]
For instance, sons and daughters could be 'smaller' to signify younger. I don't care heavily either way, @mrueschman thoughts?

**Comment by krand7** [comment]
@remomueller I personally am not a huge fan of this, as it's almost inferring age of user/children/parents and we're more likely (by disease demographic) to have users with grown children than with young/small children. Family trees generally use same sizes for things and just rely on hierarchy. Just my thoughts, I'm not in a strong opinion either way!

**Comment by remomueller** [comment]
@krand7 that's a good point, feel free to leave as is.
