### ISSUE TITLE
Sleep Apnea Risk Assessment: Units need to be on same line

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#558]
![2015-04-10_14h26_43](https://cloud.githubusercontent.com/assets/707167/7094239/9da76ae8-df8d-11e4-9255-94692da19b9e.png)

**Comment by remomueller** [comment]
This is actually an issue based on the screen width that's selected for the devise. If it didn't wrap, then feet would actually show up underneath the select tag next to it. The wrap is currently working as intended even though the two elements don't wrap at the same breakpoints (as seen above).
