### ISSUE TITLE
Sleep Apnea and BMI: One column approach might be better than two columns

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#561]
In my opinion, this:

![2015-04-10_14h40_41](https://cloud.githubusercontent.com/assets/707167/7094476/90fa263a-df8f-11e4-9b6e-16fad9d06045.png)

Looks better than this:

![2015-04-10_14h41_00](https://cloud.githubusercontent.com/assets/707167/7094478/9c3fe70a-df8f-11e4-9ac6-38f06ad5c4de.png)

**Comment by krand7** [comment]
@mrueschman it appears one column on mobile screens - but it looked funny as one column on large monitors. Mind if I close?

**Comment by mrueschman** [comment]
Go ahead. I think I mainly made this because the columns were of a different sort. Maybe in another life the tool will be reworked from the ground up.

**Comment by krand7** [comment]
And pollen count will be included :8ball:
