### ISSUE TITLE
Social profile and gender identity

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#57]
The social profile currently asks the user to enter their [biological] sex. Since this is a social profile, it makes more sense to ask for gender as gender gives the user to provide information on how they would like to identify themselves to others.

Moving forward, we will most likely change this to "Gender: _________" with a free text field to allow users the choice to identify themselves as they see fit. This is based on [Option 3 on the HRC website](http://www.hrc.org/resources/entry/collecting-transgender-inclusive-gender-data-in-workplace-and-other-surveys).

Research surveys on the other hand that do require biological sex should then require the question (and reasoning) explicitly.

**Comment by krand7** [comment]
@remomueller Do we need to change the actual attribute to :gender rather than :sex? Front end is all set

**Comment by remomueller** [comment]
@krand7 yes, we can do a migration for this (use `rename_column`). Thanks.

**Comment by remomueller** [comment]
Perhaps also provide a few auto-complete options

**Comment by krand7** [comment]
Integrate using something like this:

### Ruby

= text_field_tag 'gender', nil, autocomplete: "off", data: { object: 'typeahead', local: ["Male", "Female", "Genderqueer", "Androgynous", "Intersex", "Transgender", "Transsexual", "Cross-dresser", "Male-to-female (MTF)", "Female-to-male (FTM)"].to_json }

### Coffee

@genders = new Bloodhound (
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value')
    queryTokenizer: Bloodhound.tokenizers.whitespace
    local: $.map($("#gender").data("local"), (gender) -> { value: gender })
  )

  @genders.initialize()

  $('[data-object~="typeahead"]').each( () ->
    $this = $(this)
    $this.typeahead( null,
      name: 'genders'
      displayKey: 'value'
      source: genders.ttAdapter()
    )
  )
