### ISSUE TITLE
When clicking Login button, focus should automatically be set to Email field

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#578]
Presently I have to click twice to get into the "Email" field when I am trying to login.

![image](https://cloud.githubusercontent.com/assets/707167/7357058/45b01bbc-ecfa-11e4-80a8-73d89d5f35d5.png)

**Comment by mrueschman** [comment]
@remomueller 

This particular solution does not appear to work in FireFox 37 or IE 11. Any ideas on how to make the behavior available across browsers? I think you mentioned trying to stay away from adding JavaScript.

**Comment by remomueller** [comment]
We could add a bit more javascript to check for the field and set the autofocus for those two browsers. I'll reopen for the time being.
