### ISSUE TITLE
New pop-up login box goes off page in IE11

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#587]
![image](https://cloud.githubusercontent.com/assets/707167/7399623/06bd1d10-ee85-11e4-9aef-dfc3cfba3088.png)

**Comment by mrueschman** [comment]
@krand7 @remomueller  Is this a trivial fix? It does look sort of silly and my presumption is that a significant chunk of our users use IE.

Moving to 0.7.0. If non-trivial, take it out.

![image](https://cloud.githubusercontent.com/assets/707167/7732276/be4268f8-fef4-11e4-8e7a-066903fdcf13.png)

**Comment by remomueller** [comment]
Agreed, this should be fixed for 7.0.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.
