### ISSUE TITLE
Group 6 wording needs update.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#59]
Submitted by @mrueschman 

"In the past 7 days... My sleep quality" is not a question. Is it missing "was"?

My sleep quality [was] ... Very good / Good / Fair / Poor / Very poor?

![image](https://cloud.githubusercontent.com/assets/711826/4321691/3daad8b4-3f42-11e4-890e-8b20482c4e67.png)

**Comment by krand7** [comment]
Closed with 5.0 release
