### ISSUE TITLE
Each research topic has a progress indicator which details how thoroughly researched or supported the underlying issue is.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#590]

**Comment by mrueschman** [comment]
@krand7 @remomueller Were there additional intentions with this issue, or can we close it now with 7.0 being here?

We have had some discussions of having other "metrics" shown with research topics, yet I don't see anything on the horizon soon.

**Comment by remomueller** [comment]
This should be closed with 7.0, thanks!
