### ISSUE TITLE
Previously created research topics should be migrated into new design

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#591]
A rake task would:
- Create forum topics for each research topic
- Migrate over `text`, `description`, `state`, and `user_id`
- Reset or migrate current votes.

**Comment by pmanko** [comment]
@remomueller @mrueschman @krand7 What should we do with the old vote totals for the last generation of research topics? Since voting will now ask users whether they `endorse` or `do not endorse` a given topic, there's no good way of translating the old votes, which only had an `endorse` option. If we migrate all the old votes as `endorsing` the topic, then all of these topics will automatically have 100% endorsement, which would not capture their actual popularity.

**Comment by remomueller** [comment]
@pmanko good point, I think we should start anew since we're overhauling the system in that case.

**Comment by mrueschman** [comment]
@pmanko @remomueller

It would be nice to keep the old votes (as endorsements or whatever we call them) as a way of seeding the new system and (more importantly) not tossing out existing user contributions.

At this moment, I'd prefer to go back to something more "raw" like the vote count, as opposed to falling into the "100% endorsement" (among those who have voted on this question) trap Piotr mentions.
