### ISSUE TITLE
Allow front end UI to more easily get answers from surveys

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#596]
For example:

`def report_value(survey_slug, encounter_slug, question_slug) ... end`

```
current_user.report_value('about-my-family', 'baseline', 'country-of-origin')
```

Gets something that can be output as an array of strings or a single string:

Ex:
Country of origin would NOT return "Other" it would return the string that was filled into the "Other" choice.

Ex: No answer would return `nil`

A multi-choice "How did you hear about us" would return ["Facebook", "Social Media", "Internet"] or Empty array for no answer.

**Comment by remomueller** [comment]
I'm open for what the method is called, `report_value` can be placeholder for now.

**Comment by pmanko** [comment]
@remomueller I implemented two methods: user.answer_text and user.answer_value, along with model tests in user_test.rb. Let me know if you think the issue can be closed, or if this feature needs more work. 

I might update the Report view in the future to streamline the complex logic in these methods, possibly adding columns that make some of the conditional statements unnecessary.
