### ISSUE TITLE
Group 7 questions need to be presented more concisely.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#60]
Submitted by @mrueschman 

Would be great (now or in future) if these medical history items were presented in a much more compact format.. since now requires so much scrolling. Something akin to "scale" variables in Slice would be nice, where the answer choices are presented once across the top row and the bubbles all line up vertically below.

![image](https://cloud.githubusercontent.com/assets/711826/4321740/85cbb398-3f42-11e4-99bb-08f60e568e16.png)

**Comment by krand7** [comment]
Closed with 5.0 release
