### ISSUE TITLE
Reload Survey that contains Partners HealthCare as an option

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#601]
Mike updated some text in the YML file, so the survey should be reloaded when pushed to production:

```
Survey.load_from_file '____'
```

**Comment by remomueller** [comment]
@pmanko are we still using questions.yml and question_edges.yml? The text @mrueschman updated doesn't look like it's on any of the new surveys, can you check and close this issue if we don't need to reload an existing survey? Thanks!

**Comment by pmanko** [comment]
@remomueller @mrueschman These two files are in the deprecated section, and are only kept for legacy reasons, so we can recreate the old survey structure. All survey data is in the main directory under the appropriate survey's yml file.

Which question was mike attempting to update?

**Comment by remomueller** [comment]
We should potentially start removing duplicated areas of content and unused YML files. Also in terms of i8n, we will probably want to start from a clean slate, and not have to worry about existing files, and how we would update them.

**Comment by mrueschman** [comment]
Clean up old content files. Re-assigning to @pmanko
