### ISSUE TITLE
About Me Survey: On report, display of patient select race(s) should be cleaner

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#602]
There is a stray `,` before my selected race choice (probably accounting ahead of time for the possibility of having 1 or more options selected).

![image](https://cloud.githubusercontent.com/assets/707167/7453630/40f1a228-f239-11e4-820a-752d04b5c8ac.png)

**Comment by krand7** [comment]
I'm actually not sure why this is happening fully. I looked through the report haml file, and everything seems to be in order. I checked a few instances, and the `answer.answer_values.length` is a minimum of 2, with the first option being blank...but this doesn't happen on any other question.

I could monkey patch this and strip the first (blank) value for this particular answer, but it would be better if @pmanko can take a quick look at why this is happening in this instance?

From my console:

`survey = Survey.find_by_slug('about-me')`
`question = survey.questions.where(slug: 'race').first`
`answer_session = AnswerSession.where(survey_id: survey.id, locked: true).last`
`answer = answer_session.answers.where(question_id: question.id).first`
`answer.answer_values`

**Comment by mrueschman** [comment]
For some more context: In the report for my "real" MyApnea.Org account, there is no comma before "White".

I triggered the above after creating a new account and completing the About Me survey and viewing the report. Thanks for investigating!
