### ISSUE TITLE
Add 404 page to the site

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#604]
I was thinking about patients that may mistype a provider URL when first visiting the site. I see that an errant `/p/` link forwards to `/providers/`, which is good. Just for general purposes, however, can we have a global 404 page? I could also see patients forgetting the `/p/` part, in which case they are going to end up seeing this:

![image](https://cloud.githubusercontent.com/assets/707167/7457501/ea4fe43a-f25a-11e4-9f72-88dadcdd6d81.png)

Health e-Heart does it as follows: https://www.health-eheartstudy.org/404

**Comment by remomueller** [comment]
I'd like to also mention that GH does this as well: https://github.com/404
