### ISSUE TITLE
Users should have to accept forum terms and conditions before visiting forums

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#608]
This allows for upcoming changes to forum moderations, related to #520

**Comment by ekontos** [comment]
Not sure what I need to do for this? Don’t we already have T&C?

**Comment by krand7** [comment]
**Next step: we need the forums terms and conditions proofed and minor updates. We had discussed going through these and quality checking, including an explanation of the difference between direct medical advice and personal experience, etc.** The current text is below:

By accessing the MyApnea.Org Forums (hereinafter we, us, our, MyApnea.Org Forums ), you agree to be legally bound by the following terms. If you do not agree to be legally bound by all of the following terms then please do not access and/or use the MyApnea.Org Forums. We may change these at any time and we’ll do our utmost in informing you, though it would be prudent to review this regularly yourself as your continued usage of the MyApnea.Org Forums after changes mean you agree to be legally bound by these terms as they are updated and/or amended.


You agree not to post any abusive, obscene, vulgar, slanderous, hateful, threatening, sexually-orientated or any other material that may violate any laws of your country, the country where MyApnea.Org is hosted or international law. Doing so may lead to you being immediately and permanently banned, with notification of your Internet service provider if deemed required by us. The IP address of all posts are recorded to aid in enforcing these conditions. You agree that MyApnea.Org has the right to remove, edit, move or close any topic at any time should we see fit. As a user you agree to any information you have entered to being stored in a database. While this information will not be disclosed to any third party without your consent, MyApnea.Org shall not be held responsible for any hacking attempt that may lead to the data being compromised.

**Comment by ekontos** [comment]
How’s this:


By accessing the MyApnea.Org Forums (hereinafter we, us, our, MyApnea.Org Forums), you agree to be legally bound by the following terms. If you do not agree to be legally bound by all of the following terms then please do not access and/or use the MyApnea.Org Forums. We may change these at any time and we’ll do our best in informing you, though you should attempt to review this regularly yourself as your continued usage of the MyApnea.Org Forums after changes mean you agree to be legally bound by these terms as they are updated and/or amended.

You agree not to post any abusive, obscene, vulgar, slanderous, hateful, threatening, sexually-orientated or any other material that may violate any laws of your country, the country where MyApnea.Org is hosted or international law. Doing so may lead to you being immediately and permanently banned, with notification of your Internet service provider if deemed required by us. The IP address of all posts are recorded to aid in enforcing these conditions. You agree that MyApnea.Org has the right to remove, edit, move or close any topic at any time should we see fit. As a user you agree to any information you have entered to being stored in a database. While this information will not be disclosed to any third party without your consent, MyApnea.Org will not be held responsible for any hacking attempt that may lead to the data being compromised.

This is a moderated forum; however, entries are posted immediately after they are created. We provide this tag on all topics that may include entries that have not yet been moderated. “This topic includes at least one post that has not been approved by a moderator. Please be advised that these posts may contain sensitive material or unsolicited medical advice. MyApnea.Org does not endorse the content of these posts. The information provided on this site is not intended nor recommended as a substitute for advice from a health care professional who has evaluated you.”

**Comment by krand7** [comment]
The last section is a good addition. I would still like to see an example of the difference between medical advice and personal experience, as that is the only big issue we’ve had to deal with from a moderation perspective. Being upfront and transparent would be great from a user perspective, and a little more detail could help.

Also…to me, the beginning sounds a little intimidating! Maybe we can put the part that I just mentioned on the top, as it’s most important from a legal perspective and least scary from a user perspective.

**Comment by ekontos** [comment]
By accessing the MyApnea.Org Forums (hereinafter we, us, our, MyApnea.Org Forums), you agree to be legally bound by the following terms. If you do not agree to be legally bound by all of the following terms then please do not access and/or use the MyApnea.Org Forums. We may change these at any time and we’ll do our best in informing you, though you should attempt to review this regularly yourself as your continued usage of the MyApnea.Org Forums after changes mean you agree to be legally bound by these terms as they are updated and/or amended.
This forum is intended for users to discuss areas of interest related to sleep apnea research. It is also a space for users to share their personal experiences with sleep apnea. This forum is NOT a space to share or offer direct medical advice and MyApnea.Org has the right to remove, edit, move or close any topic or material that is related to direct medical advice. To help clarify, here is an example of a shared personal experience, “I’m sorry Member123 that you are not sleeping as well as you used to. When I experienced the same issue I met with my doctor and she lowered the pressure on my CPAP”. Here is an example of direct medical advice, “Member123 if you are not sleeping well you should lower the pressure on your CPAP.”

This is a moderated forum; however, entries are posted immediately after they are created. We provide this tag on all topics that may include entries that have not yet been moderated. “This topic includes at least one post that has not been approved by a moderator. Please be advised that these posts may contain sensitive material or unsolicited medical advice. MyApnea.Org does not endorse the content of these posts. The information provided on this site is not intended nor recommended as a substitute for advice from a health care professional who has evaluated you.”

You agree not to post any abusive, obscene, vulgar, slanderous, hateful, threatening, sexually-orientated or any other material that may violate any laws of your country, the country where MyApnea.Org is hosted or international law. Doing so may lead to you being immediately and permanently banned, with notification of your Internet service provider if deemed required by us. The IP address of all posts are recorded to aid in enforcing these conditions. You agree that MyApnea.Org has the right to remove, edit, move or close any topic at any time should we see fit. As a user you agree to any information you have entered to being stored in a database. While this information will not be disclosed to any third party without your consent, MyApnea.Org will not be held responsible for any hacking attempt that may lead to the data being compromised.
