### ISSUE TITLE
Age question is redundant in survey.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#61]
submitted by @mrueschman 

Didn't I already give you my Year of Birth? You now want this for .. confirmation? (Or to make sure you're not 1 year off?)

https://sleepepi.partners.org/edge/www.myapnea.org/research_surveys/4/545

![image](https://cloud.githubusercontent.com/assets/711826/4321767/b6e3e82e-3f42-11e4-9d02-f2ce5efd0828.png)

**Comment by krand7** [comment]
Closed with 5.0 release
