### ISSUE TITLE
The provider list should be alphabetical

### ISSUE THREAD

**Issue by ekontos** [myapnea/www.myapnea.org#613]

**Comment by mrueschman** [comment]
Presently `/providers/` is sorted by the "Official Provider Name", which is a single text entry field. I'm guessing, @ekontos , that you were anticipating sorting on something like "Last Name, First Name"? Given that we have a mixture of organizations and individuals, I think the current method is the best we can do.

**Comment by ekontos** [comment]
Maybe we can have them enter a geographic region or sort some other way? We also noted that search is key but some people may not know what name to search by so having smaller groups to sort through would be nice.

On May 5, 2015, at 8:51 AM, "Michael Rueschman" <notifications@github.com<mailto:notifications@github.com>> wrote:


Presently /providers/ is sorted by the "Official Provider Name", which is a single text entry field. I'm guessing, @ekontos<https://github.com/ekontos> , that you were anticipating sorting on something like "Last Name, First Name"? Given that we have a mixture of organizations and individuals, I think the current method is the best we can do.

—
Reply to this email directly or view it on GitHub<https://github.com/myapnea/www.myapnea.org/issues/613#issuecomment-99069590>.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by mrueschman** [comment]
I almost mentioned something like that -- i.e. other potential fields to sort/search upon. These would need to collected at the time the Provider Profile is filled out, which could cause weird issues in cases where the existing list of providers haven't completed these fields. Sort of like the scenario where we add a question to a research survey and that field is now missing for the first 3,000 users.

I think if the Providers feature blooms at some point we can revisit. 

These are the 3 things we ask from providers currently (only the first 2 are required):

![image](https://cloud.githubusercontent.com/assets/707167/7473135/c7b079f6-f306-11e4-9883-282209d2c98a.png)

**Comment by remomueller** [comment]
Hi @ekontos and @mrueschman, can you clarify what this issue should be? The providers list is alphabetical (as the title of the issue), but the discussion focuses on geographical and other provider information we don't capture. @mrueschman can we either close the issue as the provider index is sorted alphabetically and open new issues in the future, or can you rewrite the issue itself to incorporate provider details that would be searchable from the index? Thanks!

**Comment by mrueschman** [comment]
Feel free to close and we'll revisit in future if necessary.

**Comment by remomueller** [comment]
Thanks, closed by 456e0a8a7f1342236f0aafe06536388cb15b9e9e.
