### ISSUE TITLE
Users should be able to remove photos from social/provider profile

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#614]
Once you have an image uploaded, there is (seemingly) no way to remove it. You can choose a new file from your computer and save changes to update the image, yet there should be a way to explicitly remove an image in case the user chooses to do so.

**Comment by remomueller** [comment]
Not sure if there's an existing issue, but the `social_profile` model should be merged with the `user` keep images under the same model.

**Comment by krand7** [comment]
@remomueller That issue can be found here: #194

**Comment by remomueller** [comment]
Thanks, added #194 to Milestone 7.0
