### ISSUE TITLE
Login process should have 'remember me' option

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#616]
To reduce unnecessary visits to landing page and enhance experience of returning users

**Comment by remomueller** [comment]
Sites are typically moving away from the remember me button, I'm not sure having this in the interface is necessary.

**Comment by krand7** [comment]
Do we need to be more careful, since we're dealing with medical data? For instance, if somebody was to log in on a public computer and leave without logging out, they're leaving their protected info open for others to easily access.

Perhaps we can auto-check the box.

**Comment by ekontos** [comment]
Yes we need to be careful of this for exactly the reason Kyle pointed out.

**Comment by remomueller** [comment]
Also true, I think the current process of needing to login when you get to the site should be ok, so remove the "keep me signed in"

**Comment by ekontos** [comment]
Here is the latest text:

The information provided on this site is not intended nor recommended as a substitute for advice from a health care professional who has evaluated you.
