### ISSUE TITLE
Ordering of answer choices for questions 558 and 559

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#62]
Submitted by @mrueschman 

Any reason why Don't Know and Prefer not to state are at the top of the choices list for this question?

https://sleepepi.partners.org/edge/www.myapnea.org/research_surveys/4/558
![image](https://cloud.githubusercontent.com/assets/711826/4321800/1bc90d64-3f43-11e4-8a78-cf8d63f3f370.png)

https://sleepepi.partners.org/edge/www.myapnea.org/research_surveys/4/559
![image](https://cloud.githubusercontent.com/assets/711826/4321831/515952cc-3f43-11e4-8a13-16202647cc55.png)

**Comment by remomueller** [comment]
We'll have to check the ordering of these questions when the new surveys are created.

**Comment by remomueller** [comment]
These have been updated in the new survey structure in 5.0, closing issue.
