### ISSUE TITLE
For "Version Stats" report, put "Adult Diagnosed" into the table with consent and survey completion percentages

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#628]
https://myapnea.org/admin/version-stats

The percentages get based off the "Adult Diagnosed" role endorsements, so it would be nice to have these values also be present in the table.

**Comment by remomueller** [comment]
cc @ekontos, @krand7, discussing this with @mrueschman, we're going to be removing the breakdown by version, and replace it to a by month breakdown, with quarterly subtotals.

While different versions had more impact at the beginning of the study, I think the difference in time between them makes for comparison more difficult, and most data has been requested in a month by month form.

Thanks!

**Comment by remomueller** [comment]
Will also be renaming the entire page to "reports/timeline"
