### ISSUE TITLE
Test/demo a fixed width version of the site

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#633]
Currently, blowing up the browser to a huge resolution like 2560 x 1440 results in some pages on the site looking absurd:

![image](https://cloud.githubusercontent.com/assets/707167/7502588/f6f6df2a-f40a-11e4-86a6-569a21114da8.png)

![image](https://cloud.githubusercontent.com/assets/707167/7502622/3d18b38e-f40b-11e4-9514-4e4c4e005824.png)

Maybe in the interim we should add some constraints/fixes on the pages that get entirely out of hand at this resolution? @krand7 @remomueller 

My presumption is that we wouldn't start toying with a fixed width site until 8.0 or beyond.

PS. I can't stop laughing at /learn/ at this resolution.

**Comment by mrueschman** [comment]
Update: I suppose this happens generally with widescreen resolutions, e.g. 1680x1050, 1366x768. Probably best to address problematic pages sooner than later.

My presumption is that most people keep their browser open at full screen. We are probably abnormal in using the half-screen method.

**Comment by krand7** [comment]
Started with fa2b5e3cae885fa1f6e15e2966041791030a7586

**Comment by krand7** [comment]
Closed with 9.0
