### ISSUE TITLE
Customize welcome email for users who sign-up through a provider

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#635]
Change this line:

Your registration with MyApnea.Org was successful. Thank you for joining our growing network!

To:

Your registration with **[PROVIDER-NAME for]** MyApnea.Org was successful. Thank you for joining our growing network!

E.g. if provider was "Brigham and Women's Hospital, the line would read:

Your registration with Brigham and Women's Hospital for MyApnea.Org was successful. Thank you for joining our growing network!

@ekontos to confirm/tweak phrasing as necessary.

**Comment by remomueller** [comment]
@mrueschman @ekontos I added the provider name in to the welcome email for users who sign up through a provider page, if there's anything else needed, reopen the issue, as for now, I'm marking as closed. Thanks!
