### ISSUE TITLE
If you do not read consent/privacy docs through `/get-started/`, you are prompted to acknowledge changes

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#637]
New users to the site who accept the privacy policy and consent should not see this:

![image](https://cloud.githubusercontent.com/assets/707167/7521803/a1c7c582-f4be-11e4-95c8-33aeb94bec28.png)

You **DO NOT** see this page if you follow these steps:

1. Sign-up
2. Choose diagnosed role
3. Agree to consent and privacy policy (/get-started/ in URL)

You **DO** see this page if you follow these steps:

1. Sign-up
2. Choose diagnosed role
3. Click "Research Surveys" on sidebar
4. Enter and agree to consent and privacy policy (not in /get-started/)

Anticipated behavior: Both of these routes get you to the exact same spot/status/

**Comment by krand7** [comment]
I added a patch for this, but we should really go through the privacy, consent, and terms of access path. There's a lot of duplicate code (*mostly* added by me, while learning!) that could be better abstracted

**Comment by mrueschman** [comment]
Kyle's journey..

Day 1 :hatching_chick: 
Now :hatched_chick: 
Soon :chicken:
