### ISSUE TITLE
Clicking "Forums" on navbar never loads anything, something to do with new T&C addition

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#638]
If I put https://sleepepi.partners.org/edge/www.myapnea.org/forums/ in my URL bar this pushes me just fine to https://sleepepi.partners.org/edge/www.myapnea.org/forums/terms-and-conditions

However, clicking "Forums" from the navigation bars does not do this. Nothing loads. I think we've seen this sort of behavior with some other pages before.

After accepting the T&C, the primary "Forums" links work again.

**Comment by krand7** [comment]
I can't replicate on my local machine. @remomueller could it have to do with turbolinks and apache?

**Comment by mrueschman** [comment]
Maybe it's the same sort of issue as #382 ?

**Comment by remomueller** [comment]
Yes this has something to do with staging only (turbolinks/apache interaction). Closing issue.
