### ISSUE TITLE
Issues with formatting of testimonials on home page.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#64]
- **Ticket 31**: Is the guy at the bottom left the one who says "I stopped breathing...?" If so, the text is too far from his picture or it needs a bubble.
- **Ticket 14**: Text is still overlapped on the photos w the testimonials.

![image](https://cloud.githubusercontent.com/assets/711826/4322087/906e042e-3f45-11e4-9924-9e380f76e4f2.png)

**Comment by krand7** [comment]
Closed with landing page redesign in 3.0 release
