### ISSUE TITLE
Keyboard disappears in certain instances while filling out surveys on mobile device.

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#644]
We should look into reproducing this issue and resolving. My first guess is that it has something to do with JavaScript changing focus while a user is typing responses.

**Comment by remomueller** [comment]
From @michellereid:

> Are there any outstanding issues with the new survey design on mobile browsers? One user reported that her keyboard would not stay up while she was trying to enter data.

> To tickets@myapnea1.uservoice.com
> Browser Unknown 0 (OS X)
> Referrer https://myapnea.org/get-started/about-me
> Can't enter information. Keyboard won’t say up.

**Comment by mrueschman** [comment]
Reviving this issue for 8.0 as I think it gets at the heart of the issue. The first question on the About Me survey asks for date of birth and seems particularly problematic. Here's what currently occurs on my iPhone 5:

**Survey loads**
![2015-06-29 14 54 36](https://cloud.githubusercontent.com/assets/707167/8415747/0df861d8-1e6f-11e5-92b7-ea510c326ad3.png)

**User taps on Begin Survey**
![2015-06-29 14 54 42](https://cloud.githubusercontent.com/assets/707167/8415746/0df767a6-1e6f-11e5-8016-35062b724c80.png)

**User taps in Date of Birth field** (jumps and the DOB field is no longer on screen)
![2015-06-29 14 54 52](https://cloud.githubusercontent.com/assets/707167/8415748/0df8e252-1e6f-11e5-9c6a-007cde5c76d8.png)

**User must scroll down slightly to 'find' DOB field, where entry is possible (though no cursor is shown in the entry field**
![2015-06-29 14 55 03](https://cloud.githubusercontent.com/assets/707167/8415749/0df928e8-1e6f-11e5-82a6-d833e340a7ba.png)

**Comment by remomueller** [comment]
This is fixed #780 when the date entry field was changed from a keyboard entry to selection drop down boxes.

**Comment by remomueller** [comment]
Another thought, there may be an errant $("input").blur() event being fired somewhere that causes the input to lose focus and close any open keyboards.
