### ISSUE TITLE
Survey submission errors even with all questions completed.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#646]
Uservoice tickets have been coming in suggesting the surveys don't seem to allow users to submit their answers.

So far, this bug has been replicated on: 

- [ ] Internet Explorer 8

I cannot replicate this bug on Firefox, which was the browser used by one of users submitting the ticket.

**Comment by pmanko** [comment]
Remo's suggestion for fixing the missing `.map` functionality:

 https://github.com/remomueller/tasktracker/blob/master/app/assets/javascripts/external/compatibility/array_prototype_map.js

https://github.com/remomueller/tasktracker/blob/master/app/assets/javascripts/external/compatibility/array_prototype_index_of.js

This allows index_of and map to be added (looked like map didn’t exist) for IE8 and Firefox support.

**Comment by pmanko** [comment]
@remomueller @krand7 I just ran into this issue while integration-testing the research topic functionality.

I was creating a new user and going through the about-me survey flow. After filling in all the questions, the submit button was not working. Here's the screenshot:

![screenshot from 2015-05-13 13 17 30](https://cloud.githubusercontent.com/assets/711826/7616445/74a7a12c-f972-11e4-9cbf-be7f23015d90.png)

**Comment by pmanko** [comment]
js error location: 
![screenshot from 2015-05-13 13 18 30](https://cloud.githubusercontent.com/assets/711826/7616468/97f15e0c-f972-11e4-9a92-8e498e02c520.png)

**Comment by remomueller** [comment]
This looks like a separate issue that is not browser specific, recommend opening a new issue for this.
