### ISSUE TITLE
About Me Report: Exceeds horizontal width of browser window (IE/Firefox at least)

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#648]
You end up with a report that you have to scroll through vertically and horizontally. Not usable.

![image](https://cloud.githubusercontent.com/assets/707167/7591381/91f12aaa-f89b-11e4-94b5-5d3c14046e38.png)

**Comment by remomueller** [comment]
The underlying changes for this are actually fairly large, so we're going to need to put this into a larger release as these changes could introduce new bugs across other browsers.

**Comment by krand7** [comment]
For reference, a temp fix for .responsive-img within tables 
https://github.com/twbs/bootstrap/issues/10690

**Comment by mrueschman** [comment]
Revisiting old issues -- is it possible to implement a fix (temporary if necessary) for this one in 7.3? We can look to bigger/badder survey entry and report styling/look updates in future releases.

This behavior **does not** occur on any of the other survey reports (i.e. 10/11 fit on the page), so is it so much an *underlying* problem or something more specific to the "About Me" survey?

@krand7 @remomueller

**Comment by remomueller** [comment]
I'm fine changing these into 7.3, and using a temp fix (table .img-responsive for example).
