### ISSUE TITLE
Allow admins to unlock a specific user's surveys from admin interface

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#649]
Going to a specific user page, it should provide a list of surveys (and encounter), their status, the number of questions answered (out of a total), and the ability to unlock completed surveys.

**Comment by ekontos** [comment]
What is the rationale to unlock a completed survey?

On May 12, 2015, at 1:18 PM, "Remo Mueller" <notifications@github.com<mailto:notifications@github.com>> wrote:


Going to a specific user page, it should provide a list of surveys (and encounter), their status, the number of questions answered (out of a total), and the ability to unlock completed surveys.

—
Reply to this email directly or view it on GitHub<https://github.com/myapnea/www.myapnea.org/issues/649>.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by remomueller** [comment]
To allow users who submit user voice tickets the ability to go back and correct answers that they noticed they mistyped.

**Comment by ekontos** [comment]
Gotcha.

On May 12, 2015, at 1:27 PM, "Remo Mueller" <notifications@github.com<mailto:notifications@github.com>> wrote:


To allow users who submit user voice tickets the ability to go back and correct answers that they noticed they mistyped.

—
Reply to this email directly or view it on GitHub<https://github.com/myapnea/www.myapnea.org/issues/649#issuecomment-101358116>.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.
