### ISSUE TITLE
Rank the Research needs ten topics for seeding the new group

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#650]
These should be selected from the most popular research topics from round one of RtR, and messaging about how they were selected should be created.

Additionally, each topic needs a useful/meaningful description, as they will be serving as a sort of template for members submitting their own questions.

**Comment by ekontos** [comment]
Can you send a list of the top 10 currently.

**Comment by mrueschman** [comment]
Yes, having the current set of questions with the vote totals would be helpful. 

@krand7 Is it possible to get https://myapnea.org/admin/research-topics sorted by vote count? (Either pasted here or in a CSV file)
