### ISSUE TITLE
Remove 4 circular photos from landing page

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#652]
With no context, having the photos there does nothing. Hopefully we will have a video soon!

![image](https://cloud.githubusercontent.com/assets/707167/7595436/127737dc-f8b5-11e4-8594-a84ad51a8d54.png)

**Comment by krand7** [comment]
I've received backlash on landing page changes recently -- perhaps we should wait until we actually have the video. It's not *totally* without context, the community count is nearby ;)

**Comment by remomueller** [comment]
Removing from 7.0 so we can keep feedback more focused on Rank the Research (as opposed to asking PEP about multiple changes). We should revisit this when the video is made available before changing landing page.

**Comment by mrueschman** [comment]
Sounds good. We can remove these photos and do some other landing page enhancements (e.g. #657) at the time the video becomes available. Perhaps 7.1.

**Comment by remomueller** [comment]
This would be 8.0 or beyond, point releases are not intended for design changes or additions that require feedback from the group.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by mrueschman** [comment]
If the video just misses 7.0 (for instance, it arrives the last week of May), I expect to have it posted by mid-June. I anticipate the current suite of things slated for 8.0 will take us sometime into mid/late July. What we call the interim release (7.1, 8.0) to add the video and make other landing page adjustments doesn't matter much.

**Comment by remomueller** [comment]
Final draft video is here: https://www.youtube.com/watch?v=hzl_4W0Vxds

**Comment by krand7** [comment]
Closed with 9809e556aad865b4a715547397256d31bbc0cf68
