### ISSUE TITLE
Site should be updated to no-padding layout

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#654]
Except for: all landing pages (including providers' show), surveys, tools

- [x] Dashboard
- [x] About page
- [x] Steering committee
- [x] Advisory council
- [x] Partners
- [x] FAQs
- [x] Sleep Apnea
- [x] PAP Devices
- [x] Rank the Research
- [x] Community
- [x] Providers index
- [x] Forums
- [x] Settings

**Comment by mrueschman** [comment]
:+1:
