### ISSUE TITLE
Make size of sign-up input fields more reasonable

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#657]
We had a comment from Jim about the size of the sign-up input fields being absurdly long. Having input boxes that span very large widths and can accommodate hundreds of characters does seem a bit much for things like Name and Password.

![2015-05-13_14h11_27](https://cloud.githubusercontent.com/assets/707167/7617563/f5271a6a-f979-11e4-9b52-40c9517eb5a0.png)

I think we could either 1) make the font size bigger in these fields (less characters can fit) and/or 2) tweak how this form is displayed so as to not have these fields span very large widths (e.g. go with a two-column approach with some text on one side and input fields on another). Regardless, let's just seek a better balance.

**Comment by mrueschman** [comment]
Also, left align the "I am over the age of 18" checkbox and text, and make that text bigger. "Sign up!" should be bigger too!

**Comment by krand7** [comment]
Most work done with 3b820939ef31c7a4893d4693f449315035550fbb
