### ISSUE TITLE
Insert Retargeting Pixel from Connect 360 onto homepage

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#659]

**Comment by remomueller** [comment]
This seems like a questionable marketing strategy. If we implemented this, how do we provide additional messaging to users of the site that we're adding these cookies? I realize that Connect 360 states that "The user won't even notice it's there!" but MyApnea needs to continue to be transparent in it's messaging even for "beneficial" items like this. Perhaps we can get more PEP feedback on this before moving forward.

**Comment by remomueller** [comment]
As @mrueschman mentioned, this would also need to coincide with an update to the existing Privacy Policy.

**Comment by remomueller** [comment]
Code looks good for the pixel, sends across IP and referrer to the targeting pixel server and no more:

```html
<img src="https://secure.fastclick.net/w/tre?ad_id=34691;evt=27663;cat1=36894;cat2=38051;rand=[CACHEBUSTER]" width="1" height="1" border="0">
```

**Comment by remomueller** [comment]
@mrueschman assigning this to you to follow up on what type of text we need to add for this on the landing page for the moment. Also a reminder we're gearing towards RC this Friday, so we'll need the finalized text before then if possible.

**Comment by remomueller** [comment]
Also cc @ekontos for text.

**Comment by ekontos** [comment]
Here is the text:

To enhance the user experience, this site enables the use of cookies and remarketing services to target ads to you based on your visit to MyApnea.Org<http://MyApnea.Org>.

**Comment by remomueller** [comment]
Thanks @ekontos! Assigning to @krand7 to add this onto bottom of landing page (for styling).
