### ISSUE TITLE
Research Topic Polish

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#660]
- [x] Update/Add integration tests for research topic functionality.
- [x] Add progress indicator for first-topics
- [x] Add vote validation to prevent user from skipping
- [x] First topics should only reload the necessary components
- [x] rt.description appearance should be polished - quotes are odd
- [x] Add scroll container to rt.description
- [x] 'Great Job' modal appears whenever user only has 10 votes, should be only after the get-started process
- [x] New research topic creation should redirect instead of render view when topic successfully created
- [x] Moderators should be able to edit 
- [x] Research topic discussion should be visible from 'show' page
- [x] Show page should include a progress bar

**Comment by krand7** [comment]
Also allowed moderators to edit progress of research topic, and easily edit topic posts with e600ff3b5150f9800b91e60952c131f5b9aab8e1
