### ISSUE TITLE
Remove transparency from top navigation bar

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#666]
![image](https://cloud.githubusercontent.com/assets/707167/7660011/7ad58cb4-fb14-11e4-90d3-96f9b1eef84d.png)

Navbar can be a solid color.

**Comment by krand7** [comment]
Heard positive remarks from several people about it being 'fun' and less intrusive. Mobile dropdown shifts to solid color though, for usability -- related to #745

**Comment by krand7** [comment]
Also closing because of the issue number
