### ISSUE TITLE
Validation and verification of answers to survey questions.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#67]
How do we ensure data quality on surveys?

## Possible solutions:
- Allow questions to be skipped and returned to at a later time, perhaps with a "Skip and come back to later" button. 
- Before a survey is finalized, make sure all questions are answered. There could be a screen before the report which lists unanswered questions and allows users to jump quickly to the questions they need to answer.
-  Make the option "Prefer not to answer" available for all questions.
- Implement system for data validation to ensure answers are of the correct type and/or range.

**Comment by krand7** [comment]
Big leftover thing is to make sure all answers have 'Prefer not to answer'. I'll go through each survey and make sure this is available
- [ ] About me
- [ ] About my family
- [ ] Additional information about me
- [ ] My health conditions
- [ ] My interest in research
- [ ] My quality of life
- [ ] My risk profile
- [ ] My sleep apnea treatment
- [ ] My sleep apnea
- [ ] My sleep pattern
- [ ] My sleep quality
