### ISSUE TITLE
On dashboard view of forum posts, make sure profile images fit properly

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#671]
This one sort of escapes the boundaries of the forum title container section:

![image](https://cloud.githubusercontent.com/assets/707167/7709185/30b7ce22-fe29-11e4-899a-42b492217aba.png)

**Comment by mrueschman** [comment]
The new look is nice!

![image](https://cloud.githubusercontent.com/assets/707167/7731532/157fcd0a-feef-11e4-82c1-4c4acb7a2b02.png)

What are your thoughts about removing the small white border around the avatars? Remo mentioned this being related to the way that Bootstrap handles thumbnails. @krand7 

The "thumbnail" effect is even more present (i.e. bigger border) on the forum index and forum threads.

**Comment by krand7** [comment]
I initially removed the border, but it looked odd and out of place. Went with the smaller border instead, which is why you can see it looks different than in the forums
