### ISSUE TITLE
Submitting research question without description causes crash

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#673]
If I leave the "Describe why you.." field blank, the form submits and throws a "We're sorry.." message. 

https://sleepepi.partners.org/edge/www.myapnea.org/research-topics

![image](https://cloud.githubusercontent.com/assets/707167/7730944/38773e0a-feeb-11e4-971a-bcde437c5d33.png)

**Comment by krand7** [comment]
@pmanko did you address this in #427 ?

**Comment by mrueschman** [comment]
@remomueller Maybe you could take a look at this issue? Thanks.

**Comment by remomueller** [comment]
Looks fixed, just tried on stable. Closing issue.
