### ISSUE TITLE
When a user has a research topic under review, change "pending_review" to something more palatable

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#675]
![image](https://cloud.githubusercontent.com/assets/707167/7731108/26f87c6a-feec-11e4-8397-171d22e2f68c.png)

Remove the underscore in the place(s) where the topic status is shown to the user. Check how other statuses are written/presented as well.

**Comment by krand7** [comment]
Closed with eb7f49634bf65808526d3af48d3c90d246c135b3
