### ISSUE TITLE
On Windows, RtR question text and description text are same size

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#680]
![image](https://cloud.githubusercontent.com/assets/707167/7733273/0e17ae54-fefc-11e4-910a-6983f7e32388.png)

The question needs to be more prominent (e.g. bolder, bigger, something along those lines). I have noted that on Mac there is a distinction, yet this doesn't seem to carry over to Windows.

**Comment by ekontos** [comment]
Agree. The styling could be improved.
