### ISSUE TITLE
Replace RtR intro text with what Emily suggested

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#684]
Something along these lines.. also could be tweaked with how we go with #683 

The questions you have about sleep apnea are important. MyApnea.Org is different in that it is focused on patient-centered research. Who else knows more about your condition and your lived experience than you? 

This tool offers a way for you to let other members (patients, providers and researchers) know what questions matter to you most. 

The end goal is to take a top rated question (a question that has received many “endorsements”) and for researchers to develop a grant proposal or study investigation on those questions that currently lack data. Top rated questions that have already been well researched will be reviewed and presented in the Research Highlights section of MyApnea.Org.

Let's get started with 10 research topics. Once you click 'Get Started', you'll see a series of ten research questions that have been submitted by our members. You can “Agree” if you think it is an area that should be researched or you can “Disagree” if you don’t think it is of significant importance. We encourage you to add a comment to help explain your vote.

Once you're finished with these ten, we'll bring you to the full view, where you can see the most popular and most discussed topics, and get the chance to ask your own questions.

**Comment by krand7** [comment]
Also, for the outro (from @mrueschman ):

>It looks like you're really getting the hang of this. Why don't you try propsing your own research question? Or, you can continue on and see all of the research topics that are currently being voted on, and read the state of the research for topics that have been approved.
