### ISSUE TITLE
Add blurb of introductory text on RtR index page

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#685]
I think there should be be some sort of introduction to the RtR index. Assume the case where someone completed the tutorial, went on a 6-month trip to the Serengeti, and has now returned to MyApnea.Org. How does he/she know what is going on here? (Alternate scenario: A user gets amnesia.)

![image](https://cloud.githubusercontent.com/assets/707167/7750510/a15b51e2-ffa2-11e4-98bb-c9128ab6e2f2.png)

Maybe some text along the lines of:

> Let us know what research questions matter to you most. Join the community in voting and discussing research topics submitted by members like yourself. We will take the most endorsed questions and translate them into Research Highlights and proposals for future studies of sleep apnea.

**Comment by ekontos** [comment]
Perfect text. Agree on addition.

________________________________
