### ISSUE TITLE
Learn page: In IE (11), videos are shown "above" the top navbar and sub-navigation links

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#692]
Before scrolling:

![image](https://cloud.githubusercontent.com/assets/707167/7797506/04331ac8-02bb-11e5-933f-8cf4d637bcd8.png)

After scrolling (FAQs is covered by the video box):

![image](https://cloud.githubusercontent.com/assets/707167/7797514/1385a464-02bb-11e5-9f60-ad6b92e6a13c.png)

Another example with Shaq video:

![image](https://cloud.githubusercontent.com/assets/707167/7797523/272c2240-02bb-11e5-93c9-878ab733dd8d.png)

**Comment by remomueller** [comment]
Hey @krand7, I'm going to take a stab at this for the moment, thanks!

**Comment by remomueller** [comment]
For reference, found the solution here: http://stackoverflow.com/questions/7054580/youtube-iframes-sitting-on-top-of-fixed-position-element-in-chrome
