### ISSUE TITLE
Refactor the Rank the Research tutorial

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#698]
This observation was pointed out by multiple PEP members upon review of the 0.7.0 beta. Either add a "back" button into the AJAX that is presenting the tutorial at present or modify the tutorial in such a way so as to not change the behavior of the web browser back button.

**Comment by mrueschman** [comment]
Other additions that have been requested (perhaps spawn separate issues):

- Add progress indicator (e.g. 5 / 10 question when you're on the 5th question)
- Add ability to defer vote on a question to a later time
- (Maybe) Shorten the tutorial to 3-5 questions

**Comment by krand7** [comment]
My hesitation about making too many changes to this is that data completion seems to suggest that the current format is working in our favor. If you check from the admin dashboard, there's only one member who has started the research topic tutorial and not finished. The questions presented during this process have a *much* higher number of votes (currently 180 compared to 50 and below), which was the goal when we first designed this layout. 

I definitely see the concern for not being able to use the 'back' button to return to previous questions, and the current progress indicator could show 5/10 as well as 50%. I can make the changes to the indicator, but I think restructuring the urls, at this point, is outside of the scope of v9, as the index and show pages took precedence

**Comment by krand7** [comment]
Data completion rates remain remarkably high, closing for now.
