### ISSUE TITLE
Add disclaimer to learn/pap page

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#702]
@ekontos sent this along:

> *This information is provided for informational purposes and as general guidance only.  Patients should refer to the cleaning and maintenance instructions provided with your specific equipment.  If you did not receive maintenance and cleaning instructions with your equipment, please contact your equipment provider to obtain instructions.

**Comment by krand7** [comment]
Closed with 9a85a8b0210189caefbfaea28397ee4237928652
