### ISSUE TITLE
Add didgeridoo research highlight

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#704]

**Comment by krand7** [comment]
Susan said that she wanted @ekontos to review the blog, so I'll wait for sign off from her

**Comment by mrueschman** [comment]
@ekontos I think this was brought up last week at some point and I can't recall exactly what was said. Did you give approval to prepare this research highlight based on the the document Susan sent in the last week of May? 

We can do this for 7.2 if you think it's good to go (I imagine you do).

**Comment by ekontos** [comment]
Here it is. All set for 7.2
