### ISSUE TITLE
Work with research highlight authors to incorporate more multimedia elements

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#705]
Our highlights have a lot of text -- including any relevant images/graphics/embedded videos might enhance these offerings.

To start, let's contact each of the authors of our existing highlights and see if they have any initial suggestions on this front. We will also do our own searching.

**Comment by remomueller** [comment]
@mrueschman, we're closing in on our RC this Friday. Is this issue closed, or will it have updates before 8.0.0 release gets frozen? Thanks!

**Comment by mrueschman** [comment]
Mostly aroused interest around the time of the didgeridoo article preparation. Given the lack of follow-up, I think this is just a principle (i.e. ask authors if they can include non-textual elements) to keep in mind for future articles. Close away @remomueller

**Comment by remomueller** [comment]
Thanks, closing for now. New issues can be added when we get more specific content in the future.
