### ISSUE TITLE
Why do users need to be logged in to see Research Highlights?

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#708]
https://sleepepi.partners.org/edge/www.myapnea.org/research-topics/accepted

These pages would be valuable for google and other search engines to have access to as well. I think we should make these available publicly.

**Comment by remomueller** [comment]
This is similar to #709.

**Comment by krand7** [comment]
Closed with 26e52eb11e1c2542ea4fcba325c356d3217230a7
