### ISSUE TITLE
Rank the Research should be publicly viewable

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#709]
Similar to the Research Highlights, Rank the Research should also be publicly viewable.

We need to encourage users to explore the site more without forcing them to login.

**Comment by mrueschman** [comment]
Noticed this as well this morning, slightly disappointed in not
catching it sooner (too much signing up first and not browsing logged
out).

I think we need this before 8.0.

**Comment by remomueller** [comment]
Ok, moving into 7.1.
