### ISSUE TITLE
Additional Information About Me should default to the detailed report

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#711]
There is no summary report, so this should go immediately to /surveys/additional-information-about-me/report-detail

**Comment by remomueller** [comment]
It turns out that "Additional Information About Me" actually has a custom report that includes a breakdown of BMI, but the report is not calculating it correctly at the moment. I'll fix this when I update the custom report back end to pull the correct values by encounter in issue #781.

**Comment by remomueller** [comment]
Additional Information About Me now displays BMI properly, fixed in commit 1187c4abcde590f847e7f6284352b1c8de9048b1
