### ISSUE TITLE
Video makes page exceed horizontal width of browser

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#714]
![image](https://cloud.githubusercontent.com/assets/707167/7935542/ca2c8f62-08ff-11e5-8451-a3fd49eac25a.png)

Happening to me on Windows -- I can now scroll the window side-to-side.

**Comment by krand7** [comment]
It looks like it's not the video itself, but some CSS that changed with the switch to a no-padding layout. I'll look into it!
