### ISSUE TITLE
Make it easier to edit/modify incoming Rank the Research submissions

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#719]
Currently there doesn't seem to be a way to edit/modify the Rank the Research submissions. I can "Moderate" and "Delete" them. 

I wanted to do this today for an incoming question that had some minor typos/grammar edits (e.g. "loosing" to "losing"). @remomueller went ahead and modified it in the production database before we approved this question.

Putting in 7.1 in case it's a plain/simple change, otherwise it can be pushed later.

**Comment by krand7** [comment]
Temp fix in the admin dashboard (see d93b0ea8c34405fec9ddcf2e898b187d48faf63e), will wait to revisit for 8.0
