### ISSUE TITLE
Make Jessie's email a clickable link on research highlight

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#722]
![image](https://cloud.githubusercontent.com/assets/707167/7945614/e725b676-093f-11e5-8b05-e4fc5c9856d6.png)

**Comment by remomueller** [comment]
Challenging @mrueschman to do a pull request for this one!

Hint from

```haml
You can email me at email@address.com to contact me.
```

```haml
You can email me at
= mail_to 'email@address.com'
to contact me.
```

**Comment by remomueller** [comment]
Closed in 7-2-stable
