### ISSUE TITLE
Landing page breaks on iPhone 5 portrait display

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#728]
Reported by @ekontos -- the addition of the video and/or other tweaks makes the page go awry in portrait mode on the iPhone (in Safari and Chrome).

Also, the big "Join Now" button exceeds the width of the display. Can it scale?

**Comment by remomueller** [comment]
Closed by 7371711c37fa0b68e3970405fd2420a2f0a654ca
