### ISSUE TITLE
Landing page: Video should have max width set

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#750]
Video plays normally, but the preview thumbnail is **enormous**!

![image](https://cloud.githubusercontent.com/assets/707167/8091216/848d9e24-0f80-11e5-9f62-0bd2db4570d5.png)

**Comment by krand7** [comment]
Seems as it was closed with 983635b0c8bbabfc11cdf83ac4a691c123ec16a2

**Comment by remomueller** [comment]
It's not actually the size of the thumbnail that @mrueschman is referring to, it's the size the video takes up on larger screens (it's full width on 1440px monitor). The video should have a max width set. If a user wants full screen, they can see that in the controls.

**Comment by krand7** [comment]
I believe that's a separate issue. The old video actually had an enormous thumbnail (as you can see in the screenshot) that only showed about 50% of the MyApnea logo because it was so weirdly large. I'll change the description

**Comment by mrueschman** [comment]
Yeah, the original issue has seemingly cleared up. 

Compare above to now:

![image](https://cloud.githubusercontent.com/assets/707167/8211960/25f7a258-14e7-11e5-9a8b-5af5499a046d.png)

**Comment by remomueller** [comment]
Correct, I uploaded a different thumbnail to the YouTube video, thanks for renaming the issue!
