### ISSUE TITLE
When user deletes own forum posts, these should not show up as Pending Review or be hidden from admins

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#758]
This sequence is possible:

1. User makes post
2. User deletes post (post is no longer shown)
3. Admins see that there is a post "Pending Review" (cannot be seen)

In this scenario, when a user deletes his/her own post, we should track who has deleted the post and possibly set it to hidden. @remomueller

**Comment by remomueller** [comment]
Agreed that status should be changed to `hidden` and new column to be added `deleted_by_user_id`

**Comment by sleepish** [comment]
Remo,
May I ask why you are keeping deleted posts?
Thanks.

**Comment by remomueller** [comment]
Hi @sleepish, we use this approach as it allows us to restore data in cases in which accidental deletion occurs. You can take a look at this post for more information on pros and cons: http://stackoverflow.com/questions/502501/database-to-delete-or-not-to-delete-records

This isn't to say though that data can't be deleted permanently, and the team will do so if and when deemed appropriate.

**Comment by sleepish** [comment]
Thanks for reply and link, appreciated
