### ISSUE TITLE
Remove privacy blurb on bottom of landing page

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#766]
These aspects of the site are now described in the Privacy Policy, which we were waiting to have approved by the IRB.

@krand7 @remomueller 7.2.2 or 7.3 or 8.0?

**Comment by remomueller** [comment]
Let's do 7.3, point releases should mainly be bug fixes (one offs).

**Comment by mrueschman** [comment]
Sounds good!
