### ISSUE TITLE
Member is getting 200% completion for 'My Risk Profile' survey

### ISSUE THREAD

**Issue by mcailler** [myapnea/www.myapnea.org#771]
This is causing her to be prompted to 'Work on this survey now' rather than being able to visualize her data.

**Comment by mrueschman** [comment]
Maybe we could take a look at a data export and see if this user's data look.. different? @remomueller 

I think we would need to add user_id to the data export. The risk profile questions are all there.

**Comment by remomueller** [comment]
We'll need to do the following:

- [ ] (1) Add the missing validation to `answer.rb`:

```ruby
# Model Validation
validates_uniqueness_of :question_id, scope: [:answer_session_id, :deleted]
```

- [ ] (2) Figure out a strategy to remove duplicates

- [ ] (3) Make sure that `process_answer` in `answer_session.rb` correctly handles a validation failure event.
