### ISSUE TITLE
Email addresses in forum posts are turning into @-mentions

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#773]
![image](https://cloud.githubusercontent.com/assets/707167/8456699/39c7a928-1fdb-11e5-9cb6-80948cc439f8.png)

**Comment by remomueller** [comment]
It appeared to have a weird symbol `&#8203;` between the `d` and the `@`. Removing this fixed the issue.

**Comment by remomueller** [comment]
Here's what the symbol was:

http://stackoverflow.com/questions/2973698/whats-html-character-code-8203

> Unicode Character 'ZERO WIDTH SPACE' (U+200B)
> this character is intended for line break control; it has no width, but its presence between two characters does not prevent increased letter spacing in justification
