### ISSUE TITLE
'utmx is undefined' error in IE

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#774]
This error pops up when visiting 7.3 in IE:

![image](https://cloud.githubusercontent.com/assets/707167/8463585/931b8e80-2009-11e5-9577-023fe5c56820.png)

**Comment by krand7** [comment]
Seems like it has something to do with google website optimizer (http://www.analyticsmarket.com/blog/website-optimizer-with-google-analytics)
