### ISSUE TITLE
Friendlier "access denied" messages are needed.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#78]
![myapnea org](https://cloud.githubusercontent.com/assets/711826/4507178/3b63c25e-4b0a-11e4-92da-6c5fddf1c172.png)

The error above shows up when a user tries to click the "Add a new research question" button without creating a social profile. The error needs to be more helpful. In general, there needs to be a way to add relevant messages.

**Comment by remomueller** [comment]
This is related to issue #194, and will most likely become irrelevant. Closing this issue.
