### ISSUE TITLE
Update how Date of Birth is captured

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#780]
Current Date of Birth entry causes issues for some users on different browsers/devices. Simplify the date of birth input to work more consistently across all browsers.

**Comment by remomueller** [comment]
This is related to issue #644.

**Comment by mrueschman** [comment]
@remomueller 

Would we be able to fix something like the below? Kind of cruel to admonish users when they haven't even had a chance to select an item from the three dropdowns yet!

![image](https://cloud.githubusercontent.com/assets/707167/9496830/406f78ce-4be0-11e5-8928-d3b27f3789c1.png)

**Comment by remomueller** [comment]
@mrueschman Perhaps, but how do we differentiate from users who actually missed those, and those who are just starting?
