### ISSUE TITLE
Add text to secondary answer templates that don't currently have text values

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#802]
In order to be consistent, and for informative API calls
<code>AnswerTemplate.where.not(parent_answer_template_id: nil).where(text: nil)</code>

**Comment by remomueller** [comment]
We should probably add a rake task for this in `surveys.rake`

**Comment by krand7** [comment]
Sounds good, list of the questions for reference
<code>AnswerTemplate.where.not(parent_answer_template_id: nil).pluck(:name)</code>

**Comment by krand7** [comment]
@remomueller add the following to release notes
<code>bundle exec rake surveys:add_text_values_to_secondary_templates</code>
