### ISSUE TITLE
Alignment on survey questions with multiple columns is whacky

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#827]
![image](https://cloud.githubusercontent.com/assets/707167/9501639/6da7ddee-4bfa-11e5-8b78-67c19d4bcc15.png)

The 1) question text, 2) answer choice boxes, and 3) skip this question option all appear to be "centered" on different axes. 

Single columns don't seem as bad (only the 'skip this question' appears off kilter):

![image](https://cloud.githubusercontent.com/assets/707167/9501664/914f769e-4bfa-11e5-9cfa-68b349c540ea.png)

**Comment by krand7** [comment]
Larger survey changes will be made in 10.0
