### ISSUE TITLE
Review survey descriptions to ensure that they are indeed descriptive

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#829]
Especially for ResearchKit -- we'll want better descriptions!

**Comment by mrueschman** [comment]
- [ ] About Me
- [ ] About My Family
- [ ] Additional Information About Me
- [ ] My Health Conditions
- [ ] My Interest in Research
- [ ] My Quality of Life
- [ ] My Risk Profile
- [ ] My Sleep Apnea
- [ ] My Sleep Apnea Treatment
- [ ] My Sleep Pattern
- [ ] My Sleep Quality

**Comment by mrueschman** [comment]
@krand7 @remomueller OK -- I made some revisions and posted them above. I left the boxes unchecked in case you want to use those to indicate the change was made in the database. I don't know if these actually count as "descriptive" in all cases, but I would be fine fielding other suggestions/edits now or later. I'm particularly interested in how these will look/feel in the mobile app.

**Comment by remomueller** [comment]
Thanks, changes have been made!
