### ISSUE TITLE
Add SWHR to partners page

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#844]
About SWHR
The Society for Women’s Health Research (SWHR®), is a national non-profit based in Washington D.C. that is widely recognized as the thought-leader in promoting research on biological differences in disease. SWHR is dedicated to transforming women’s health through science, advocacy, and education. Founded in 1990 by a group of physicians, medical researchers and health advocates, SWHR aims to bring attention to the variety of diseases and conditions that disproportionately or predominately affect women. For more information, please visit www.swhr.org. Follow us on Twitter at @SWHR.

![swhr_logo_final](https://cloud.githubusercontent.com/assets/707167/10228418/7ed488c6-6840-11e5-93ce-cb9f3878afd5.png)

**Comment by remomueller** [comment]
This was completed in 8.3, closing.
