### ISSUE TITLE
Incorporate PEP corner onto site

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#853]
Per @ekontos , there will be PEP Q&As coming out regularly now. We will start by posting them on the forum. This issue is for the step beyond that where these Q&A are published elsewhere on the site (e.g. linked from Team page) as static pages. We may want to have further discussion about how to fit them in.

**Comment by krand7** [comment]
Clearing milestone until we know more about how this will be structured, and until we have more than one. I could see them being incorporated as links from the team page, with their own separate page
>myapnea.org/team/matt-epstein

**Comment by ekontos** [comment]
Susan would like a dedicated space for this ASAP. We will have another highlight every month. A link from their team page is fine. We need another solution besides forum post.

On Nov 6, 2015, at 11:36 AM, Kyle Rand <notifications@github.com<mailto:notifications@github.com>> wrote:


Clearing milestone until we know more about how this will be structured, and until we have more than one. I could see them being incorporated as links from the team page, with their own separate page

myapnea.org/team/matt-epstein<http://myapnea.org/team/matt-epstein>

—
Reply to this email directly or view it on GitHub<https://github.com/myapnea/www.myapnea.org/issues/853#issuecomment-154462385>.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.
