### ISSUE TITLE
Add new answer choices to My Sleep Apnea question about doctor that spoke about sleep apnea

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#857]
![2015-10-23_10h55_24](https://cloud.githubusercontent.com/assets/707167/10695952/92e3f60e-7974-11e5-8e60-5277060b7b8b.png)

> For which doctor first spoke with you about sleep apnea--add pulmonologist, neurologist, psychologist, psychiatrist

Consider how adding choices affects the existing choices, since in an ideal world "Other" and "Prefer not to answer" would still come last. Do we need to set positions for answer choices?

**Comment by mrueschman** [comment]
Also, "Other" does not have a "specify" field pop up to fill in an alternative response. Add an "Other, specify" type field during updates.

**Comment by krand7** [comment]
@remomueller @mrueschman When you updated these answer choices in the survey builder, did you also add an 'other' answer option?

**Comment by remomueller** [comment]
No it was only the addition of new options. The other field didn't get a corresponding text field entry.
