### ISSUE TITLE
Add new options in My Risk Profile questions -- maybe make new survey entirely

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#858]
![2015-10-23_10h58_21](https://cloud.githubusercontent.com/assets/707167/10696302/fc477e7c-7974-11e5-87a1-314fd3597840.png)

> We should do the following--for surveys asking how long you have had symptoms X before being diagnosed- add 2 to 5 years; 5 to 10 yrs; greater than 10 years

Consider changing "N/A" to "I do not experience this symptom".

Given that new answer choices would not align with existing choices (e.g. "12+ Months" now does not make sense), we may want to re-make the My Risk Profile survey entirely. Not sure how this would impact the My Risk Profile report.

**Comment by mrueschman** [comment]
Note: I think this also applies to questions on the My Sleep Apnea survey.

![image](https://cloud.githubusercontent.com/assets/707167/11035284/6afabcec-86bf-11e5-9008-be1801e761c8.png)

Might need new version of survey there as well.

**Comment by ekontos** [comment]
let's talk about survey modification since I am putting in an amendment this week.

________________________________

**Comment by krand7** [comment]
Closed with archiving answer templates in #882
