### ISSUE TITLE
Date fields on surveys should allow for years after 1997

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#863]
We are adding a pediatric survey that asks for the child's date of birth, which will necessarily be sometime in the past 8 years.

Currently, adding any sort of date question to a survey locks you in with 1997 being the most recent year selectable.

![image](https://cloud.githubusercontent.com/assets/707167/10972064/8e27b5ac-83a5-11e5-9818-b2c5281a1dbe.png)

**Comment by krand7** [comment]
Removed >18 validation in general, since adults already consent to being over 18 years old when signing up, and this will allow for more flexibility moving forward
