### ISSUE TITLE
Questions that "branch" from others (using parent template values) cannot have labels

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#870]
It seems as if you can't have any sort of labeling next to questions that "branch" from other fields. For instance, a "specify" field after clicking "Other". In the instance below, we want to have multiple questions show up after a user selects "Yes" to a certain treatment type for their child.

![image](https://cloud.githubusercontent.com/assets/707167/11099619/67863d5e-887a-11e5-910b-2e9a313d1349.png)

**Comment by remomueller** [comment]
Surveys in v16 are handled by Slice, closing issue.
