### ISSUE TITLE
Make topic view counts available to all users

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#880]
Either on the topic itself, as currently done for admins:

![image](https://cloud.githubusercontent.com/assets/707167/11372564/342ef816-929c-11e5-91cc-99042b54d48f.png)

Or on the forum topic index?

**Comment by krand7** [comment]
Seems sufficient to do on the forum topic index, double-checked with other forums and most seem to go this route.

**Comment by mrueschman** [comment]
Agreed!
