### ISSUE TITLE
Add ability to archive questions

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#888]
Related to the issue about arching answer templates..

In the My Sleep Apnea Treatment, a change was made to the final question to insert the word "current". We archived all the old answer templates and created new ones under the new question, primarily to have the capability down the line of distinguishing who answered the question at which timepoint. However, we now need the capability of archiving the "old" question itself such that it won't show on the survey.

![image](https://cloud.githubusercontent.com/assets/707167/11846394/720ac2a4-a3e6-11e5-9c13-03cd7aa5772f.png)

**Comment by krand7** [comment]
From convo with @mrueschman : taking different approach - will only show questions that have unarchived answer templates.

**Comment by krand7** [comment]
JK - due to has_many_and_belongs_to and survey_question_order table, was much simpler to archive questions as a whole. This should also look nicer in the data export, be more consistent, and prevent the builder from having to go in and mark all answer templates as archived.
