### ISSUE TITLE
On symptoms custom reports (My Risk Prof / My Sleep Apnea), tweak wording for new answer choices

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#889]
The "My Risk Profile" and "My Sleep Apnea" surveys were updated on staging to add more answer choices to the symptoms questions. Check to confirm that the custom report works correctly with the new answer choices in place.

![image](https://cloud.githubusercontent.com/assets/707167/11846503/f1b67d9a-a3e6-11e5-8df4-f8d3089ab247.png)

Also, this wording should be phrased differently between these two surveys. "My Risk Profile" (screenshot above) has nothing to do with evaluations for sleep apnea or diagnosis.

I think the particular phrasing to confirm/change/remove is the "X% of MyApnea users report experiencing this symptom one year.." We could choose a new cutoff now that we have expanded answer choices, e.g. "at least 3 years.." (choose 3-5 years, 6-10 years, 11 or more years).

**Comment by krand7** [comment]
Will need the updated question options to go live before doing this - can do a 9.3 point release with the following changes:

___sleep_apnea_symptoms_statistics.html.haml__

```ruby
- ri5 = ReportItem.new(answer_option_counts, answer_template, 5)
- all_ri = [ri1, ri2, ri3, ri4, ri5]
= ri2.percent_raw + ri3.percent_raw + ri4.percent_raw + ri5.percent_raw
```
```haml
%span.primary-orange= ri2.percent_raw + ri3.percent_raw + ri4.percent_raw + ri5.percent_raw
        of MyApnea users report experiencing this symptom at least one year before diagnosis.
```

**Comment by krand7** [comment]
Temporarily commented out the soon-to-be-incorrect wording
