### ISSUE TITLE
Add slug to pep-corner (team_member) for nicer url structure

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#893]

**Comment by remomueller** [comment]
@mrueschman, these could be pulled into blog posts under a 'PEP Corner' category?

**Comment by mrueschman** [comment]
Yes, I think that sounds like a good approach

**Comment by remomueller** [comment]
Removing from milestone, the blog can handle the PEP corner (as a category) if needed, will wait on seeing if the PEP wishes to add more articles to the PEP corner going forward.
