### ISSUE TITLE
Add simplified article on Complex Sleep Apnea to Learn Page

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#899]
Article by Robert Thomas.

**Comment by remomueller** [comment]
Would this be a link to the article on another page? The learn page isn't designed for large paragraphs of text.

**Comment by mrueschman** [comment]
I am thinking a new panel called "Complex Sleep Apnea", with the large globs of text being on the page that is linked to.

**Comment by remomueller** [comment]
Should we replace an existing panel? We'll also need a photo to use for the article then.

**Comment by mrueschman** [comment]
Why replace when you can go to 4 rows?! 

I've been having fun finding Creative Commons photos on Flickr.. I'm sure we can get something for this topic!

**Comment by remomueller** [comment]
Ok, will see if it's easy enough to have it centered for the last one.

**Comment by sleepish** [comment]
I can draw you a picture of a mad-crazy-looking person if you like! :-)

On Fri, Feb 5, 2016 at 11:40 AM, Michael Rueschman <notifications@github.com

**Comment by mrueschman** [comment]
Fix styling on this page: 

- [ ] https://myapnea.org/learn/risk-factors-for-sleep-apnea
