### ISSUE TITLE
Change "Research Highlights" title on dashboard to "Highlights"

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#903]
![image](https://cloud.githubusercontent.com/assets/707167/12980668/7c907f10-d0ab-11e5-88d5-4e20a3e7760b.png)

We often post items here now that have nothing to do with research, so "Highlights" alone seems more fitting.

**Comment by remomueller** [comment]
I'm assuming the URL slugs should be updated to match as well.

**Comment by mrueschman** [comment]
Yeah, changing the slugs is another topic worth discussing.
