### ISSUE TITLE
Make it more evident how one can comment / join conversation in forum when not logged in

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#907]
We have had a couple UserVoice tickets ask, "How do I comment [on the forum]?", and SBG brought up a similar refrain. My idea would include having a more prominent "mock" comment area when browsing the forums in a not-logged-in state. Users might perhaps be used to other forums and/or comments on blogs/articles where you do not need to create an account first, so they may be looking for the comment box yet finding none.

**Comment by mrueschman** [comment]
Somewhat related, but Zinta suggested embellishing the sidebar in the forums (i.e. adding more substantive messaging/introduction to the site, like on About), particularly gearing toward non-logged in users:

> Google analytics tells me that only 50% of the people who visit the page “About” drop off, which is a much better hook result than most of the other pages. Is there any chance this page could pop up when new users cruise the forum? It may be more persuasive than the current pop-up window.
Zinta

(The sample size from Analytics was fairly small).

**Comment by remomueller** [comment]
@mrueschman, should this one be put back into 11.0.0 with forum changes?

**Comment by mrueschman** [comment]
Yes, I think so.. I thought about referencing it from #921

**Comment by remomueller** [comment]
Forum changes are scheduled for 12.0.0 release

**Comment by remomueller** [comment]
@mrueschman, in 13.0.0 on staging, is this now sufficiently clear how to post a reply? If so, we can close this issue.

**Comment by mrueschman** [comment]
Agreed, closing.
