### ISSUE TITLE
Forum administrator design changes

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#91]
Here are some minor stylistic issues that can be changed to improve the forum moderation process:

- [ ] On the [Forums Admin Panel](https://myapnea.org/social/discussion/admin), the **Visit Forums** button has a title with a missing translation: `en.forum.admin.visit_forums`
- [ ] Clicking **Manage Forums** on the Forums Admin Panel doesn't do anything. I was expecting it to lead to the forum "Moderation Tools" page. Perhaps add a link to the forum moderation page here and remove the **Manage Forums** link
- [ ] The [Moderation Tools](https://myapnea.org/social/discussion/introductions/moderation) page should be more informative instead of just saying "0 topics", but instead, "Congrats, no new topics waiting to be moderated".
- [ ] The Moderation Tools page, should have better styling for topics waiting to be moderated. Currently it only shows a list of topics, without any description, or who posted them, or when.
- [ ] The **Approve** / **Spam** and **Moderate** buttons are not intuitive. They either need to be changed to visible radio boxes for approve and spam, or have it be a one-click process. The **Moderate** button should be changed to "Update Selection/Topic/Post" in the case of a two-click process.
- [ ] After moderating a post, there should be a clear indication that the post was successfully moderated, as well as a link back to "Go back to moderate other topics".
- [ ] The sizes of user pictures appear to be all over the place, some are very large, and some are very small. Choose a standard size for pictures or reduces the max size of images. The CSS should be describing the size of the image, and not the carrierwave/imagemagick resize process on the back end, as the CSS can be changed more easily.
- [ ] The text  collapses (and is VERY small) under pictures on tablet view. Tablet view should still be horizontal, otherwise it looks more like a series of pictures, as opposed to a conversation. (Pictures are less important, the text is more important)

**Comment by pmanko** [comment]
Closing outdated issue.
