### ISSUE TITLE
Forum improvements/enhancements

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#921]
An initial list, which may change over time. Some items may move to separate issues or to future releases (or be removed entirely!)

- [x] Improve the forum search, particularly in the presentation of results (e.g. highlight specific posts containing search terms
- [x] Collapse topics into single forum
- [x] Disable (or limit) "comments within comments"
- [x] Remove (?) right-hand column space that is currently wasted when browsing forums
- [x] Add ability to jump directly to the last page/post of a thread from the main forum index
- [x] Add "jump to last read post" type functionality that tracks individual user through each topic
- [x] ~~Improve experience of adding a new topic (e.g. will be able to do from main forum index; make seamless process for logged out users to sign-up / make post)~~ Moved to #939
- [ ] ~~Allow forum topics to be categorized~~ Moved to #940

**Comment by remomueller** [comment]
Moving this to 12.0.0 to keep it in a dedicated release.
