### ISSUE TITLE
Add email confirmation for new sign-ups

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#962]
Given the rash of spam posts on the forum, it would be nice to email new users a link that they could click on to verify their accounts. Verifying by email would then "allow" the user to start posting on the forum.

**Comment by remomueller** [comment]
According to this, I think it's possible for us to make the email confirmation conditional:

http://stackoverflow.com/questions/4790685/devise-is-it-possible-to-not-send-a-confirmation-email-in-specific-cases-eve

In `user.rb`

```ruby
  # Callback to overwrite if confirmation is required or not.
  def confirmation_required?
    !confirmed?
  end
```

**Comment by remomueller** [comment]
Looks like this may not currently be needed, removing from milestone.
