### ISSUE TITLE
Surveys Page

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#99]
- [ ] Surveys index should display sample charts of questions completed by other participants (see image)
  - ![myapnea-presentation05](https://cloud.githubusercontent.com/assets/316479/4940363/df56ccc8-65d9-11e4-9a10-b146d2cb4593.png)
- [ ] You should be able to see the "Surveys" index page without logging in.

**Comment by krand7** [comment]
- Providers/researchers can see aggregate data with sample surveys, while users can see their survey progress
- Currently with 5.0 you are unable to see surveys index page without logging in, is it necessary to see?

**Comment by remomueller** [comment]
This is an older design, we'll recreate a new issue if we need new design directions in the future.
