### ISSUE TITLE
Allow admins to review and perma-delete user-deleted posts

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#997]
See, this thread: https://myapnea.org/forum/problems-your-having-with-dental-appliances/2

The user probably double/triple-posted (possible other thing to check out) and now we have a break in the conversation. These comments (not nested / not replied-to) would be useful to remove from the page completely.

**Comment by remomueller** [comment]
This was done in e4e11594380db545cf32ae5a48eeb92f148eb202
